// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: M24.proto

package com.znl.proto;

public final class M24 {
  private M24() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface M240000OrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code M24.M240000}
   *
   * <pre>
   *获取活动列表
   * </pre>
   */
  public static final class M240000 extends
      com.google.protobuf.GeneratedMessage
      implements M240000OrBuilder {
    // Use M240000.newBuilder() to construct.
    private M240000(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private M240000(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final M240000 defaultInstance;
    public static M240000 getDefaultInstance() {
      return defaultInstance;
    }

    public M240000 getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private M240000(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.znl.proto.M24.internal_static_M24_M240000_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.znl.proto.M24.internal_static_M24_M240000_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.znl.proto.M24.M240000.class, com.znl.proto.M24.M240000.Builder.class);
    }

    public static com.google.protobuf.Parser<M240000> PARSER =
        new com.google.protobuf.AbstractParser<M240000>() {
      public M240000 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new M240000(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<M240000> getParserForType() {
      return PARSER;
    }

    public interface S2COrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required int32 rs = 1;
      /**
       * <code>required int32 rs = 1;</code>
       */
      boolean hasRs();
      /**
       * <code>required int32 rs = 1;</code>
       */
      int getRs();

      // repeated .Common.RewardInfo rewards = 2;
      /**
       * <code>repeated .Common.RewardInfo rewards = 2;</code>
       */
      java.util.List<com.znl.proto.Common.RewardInfo> 
          getRewardsList();
      /**
       * <code>repeated .Common.RewardInfo rewards = 2;</code>
       */
      com.znl.proto.Common.RewardInfo getRewards(int index);
      /**
       * <code>repeated .Common.RewardInfo rewards = 2;</code>
       */
      int getRewardsCount();
      /**
       * <code>repeated .Common.RewardInfo rewards = 2;</code>
       */
      java.util.List<? extends com.znl.proto.Common.RewardInfoOrBuilder> 
          getRewardsOrBuilderList();
      /**
       * <code>repeated .Common.RewardInfo rewards = 2;</code>
       */
      com.znl.proto.Common.RewardInfoOrBuilder getRewardsOrBuilder(
          int index);
    }
    /**
     * Protobuf type {@code M24.M240000.S2C}
     */
    public static final class S2C extends
        com.google.protobuf.GeneratedMessage
        implements S2COrBuilder {
      // Use S2C.newBuilder() to construct.
      private S2C(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private S2C(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final S2C defaultInstance;
      public static S2C getDefaultInstance() {
        return defaultInstance;
      }

      public S2C getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private S2C(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                rs_ = input.readInt32();
                break;
              }
              case 18: {
                if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                  rewards_ = new java.util.ArrayList<com.znl.proto.Common.RewardInfo>();
                  mutable_bitField0_ |= 0x00000002;
                }
                rewards_.add(input.readMessage(com.znl.proto.Common.RewardInfo.PARSER, extensionRegistry));
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
            rewards_ = java.util.Collections.unmodifiableList(rewards_);
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.znl.proto.M24.internal_static_M24_M240000_S2C_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.znl.proto.M24.internal_static_M24_M240000_S2C_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.znl.proto.M24.M240000.S2C.class, com.znl.proto.M24.M240000.S2C.Builder.class);
      }

      public static com.google.protobuf.Parser<S2C> PARSER =
          new com.google.protobuf.AbstractParser<S2C>() {
        public S2C parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new S2C(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<S2C> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required int32 rs = 1;
      public static final int RS_FIELD_NUMBER = 1;
      private int rs_;
      /**
       * <code>required int32 rs = 1;</code>
       */
      public boolean hasRs() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 rs = 1;</code>
       */
      public int getRs() {
        return rs_;
      }

      // repeated .Common.RewardInfo rewards = 2;
      public static final int REWARDS_FIELD_NUMBER = 2;
      private java.util.List<com.znl.proto.Common.RewardInfo> rewards_;
      /**
       * <code>repeated .Common.RewardInfo rewards = 2;</code>
       */
      public java.util.List<com.znl.proto.Common.RewardInfo> getRewardsList() {
        return rewards_;
      }
      /**
       * <code>repeated .Common.RewardInfo rewards = 2;</code>
       */
      public java.util.List<? extends com.znl.proto.Common.RewardInfoOrBuilder> 
          getRewardsOrBuilderList() {
        return rewards_;
      }
      /**
       * <code>repeated .Common.RewardInfo rewards = 2;</code>
       */
      public int getRewardsCount() {
        return rewards_.size();
      }
      /**
       * <code>repeated .Common.RewardInfo rewards = 2;</code>
       */
      public com.znl.proto.Common.RewardInfo getRewards(int index) {
        return rewards_.get(index);
      }
      /**
       * <code>repeated .Common.RewardInfo rewards = 2;</code>
       */
      public com.znl.proto.Common.RewardInfoOrBuilder getRewardsOrBuilder(
          int index) {
        return rewards_.get(index);
      }

      private void initFields() {
        rs_ = 0;
        rewards_ = java.util.Collections.emptyList();
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasRs()) {
          memoizedIsInitialized = 0;
          return false;
        }
        for (int i = 0; i < getRewardsCount(); i++) {
          if (!getRewards(i).isInitialized()) {
            memoizedIsInitialized = 0;
            return false;
          }
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, rs_);
        }
        for (int i = 0; i < rewards_.size(); i++) {
          output.writeMessage(2, rewards_.get(i));
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, rs_);
        }
        for (int i = 0; i < rewards_.size(); i++) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, rewards_.get(i));
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.znl.proto.M24.M240000.S2C parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.znl.proto.M24.M240000.S2C parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.znl.proto.M24.M240000.S2C parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.znl.proto.M24.M240000.S2C parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.znl.proto.M24.M240000.S2C parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.znl.proto.M24.M240000.S2C parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.znl.proto.M24.M240000.S2C parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.znl.proto.M24.M240000.S2C parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.znl.proto.M24.M240000.S2C parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.znl.proto.M24.M240000.S2C parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.znl.proto.M24.M240000.S2C prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code M24.M240000.S2C}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.znl.proto.M24.M240000.S2COrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.znl.proto.M24.internal_static_M24_M240000_S2C_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.znl.proto.M24.internal_static_M24_M240000_S2C_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.znl.proto.M24.M240000.S2C.class, com.znl.proto.M24.M240000.S2C.Builder.class);
        }

        // Construct using com.znl.proto.M24.M240000.S2C.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
            getRewardsFieldBuilder();
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          rs_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          if (rewardsBuilder_ == null) {
            rewards_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            rewardsBuilder_.clear();
          }
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.znl.proto.M24.internal_static_M24_M240000_S2C_descriptor;
        }

        public com.znl.proto.M24.M240000.S2C getDefaultInstanceForType() {
          return com.znl.proto.M24.M240000.S2C.getDefaultInstance();
        }

        public com.znl.proto.M24.M240000.S2C build() {
          com.znl.proto.M24.M240000.S2C result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.znl.proto.M24.M240000.S2C buildPartial() {
          com.znl.proto.M24.M240000.S2C result = new com.znl.proto.M24.M240000.S2C(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.rs_ = rs_;
          if (rewardsBuilder_ == null) {
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
              rewards_ = java.util.Collections.unmodifiableList(rewards_);
              bitField0_ = (bitField0_ & ~0x00000002);
            }
            result.rewards_ = rewards_;
          } else {
            result.rewards_ = rewardsBuilder_.build();
          }
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.znl.proto.M24.M240000.S2C) {
            return mergeFrom((com.znl.proto.M24.M240000.S2C)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.znl.proto.M24.M240000.S2C other) {
          if (other == com.znl.proto.M24.M240000.S2C.getDefaultInstance()) return this;
          if (other.hasRs()) {
            setRs(other.getRs());
          }
          if (rewardsBuilder_ == null) {
            if (!other.rewards_.isEmpty()) {
              if (rewards_.isEmpty()) {
                rewards_ = other.rewards_;
                bitField0_ = (bitField0_ & ~0x00000002);
              } else {
                ensureRewardsIsMutable();
                rewards_.addAll(other.rewards_);
              }
              onChanged();
            }
          } else {
            if (!other.rewards_.isEmpty()) {
              if (rewardsBuilder_.isEmpty()) {
                rewardsBuilder_.dispose();
                rewardsBuilder_ = null;
                rewards_ = other.rewards_;
                bitField0_ = (bitField0_ & ~0x00000002);
                rewardsBuilder_ = 
                  com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                     getRewardsFieldBuilder() : null;
              } else {
                rewardsBuilder_.addAllMessages(other.rewards_);
              }
            }
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasRs()) {
            
            return false;
          }
          for (int i = 0; i < getRewardsCount(); i++) {
            if (!getRewards(i).isInitialized()) {
              
              return false;
            }
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.znl.proto.M24.M240000.S2C parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.znl.proto.M24.M240000.S2C) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required int32 rs = 1;
        private int rs_ ;
        /**
         * <code>required int32 rs = 1;</code>
         */
        public boolean hasRs() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required int32 rs = 1;</code>
         */
        public int getRs() {
          return rs_;
        }
        /**
         * <code>required int32 rs = 1;</code>
         */
        public Builder setRs(int value) {
          bitField0_ |= 0x00000001;
          rs_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 rs = 1;</code>
         */
        public Builder clearRs() {
          bitField0_ = (bitField0_ & ~0x00000001);
          rs_ = 0;
          onChanged();
          return this;
        }

        // repeated .Common.RewardInfo rewards = 2;
        private java.util.List<com.znl.proto.Common.RewardInfo> rewards_ =
          java.util.Collections.emptyList();
        private void ensureRewardsIsMutable() {
          if (!((bitField0_ & 0x00000002) == 0x00000002)) {
            rewards_ = new java.util.ArrayList<com.znl.proto.Common.RewardInfo>(rewards_);
            bitField0_ |= 0x00000002;
           }
        }

        private com.google.protobuf.RepeatedFieldBuilder<
            com.znl.proto.Common.RewardInfo, com.znl.proto.Common.RewardInfo.Builder, com.znl.proto.Common.RewardInfoOrBuilder> rewardsBuilder_;

        /**
         * <code>repeated .Common.RewardInfo rewards = 2;</code>
         */
        public java.util.List<com.znl.proto.Common.RewardInfo> getRewardsList() {
          if (rewardsBuilder_ == null) {
            return java.util.Collections.unmodifiableList(rewards_);
          } else {
            return rewardsBuilder_.getMessageList();
          }
        }
        /**
         * <code>repeated .Common.RewardInfo rewards = 2;</code>
         */
        public int getRewardsCount() {
          if (rewardsBuilder_ == null) {
            return rewards_.size();
          } else {
            return rewardsBuilder_.getCount();
          }
        }
        /**
         * <code>repeated .Common.RewardInfo rewards = 2;</code>
         */
        public com.znl.proto.Common.RewardInfo getRewards(int index) {
          if (rewardsBuilder_ == null) {
            return rewards_.get(index);
          } else {
            return rewardsBuilder_.getMessage(index);
          }
        }
        /**
         * <code>repeated .Common.RewardInfo rewards = 2;</code>
         */
        public Builder setRewards(
            int index, com.znl.proto.Common.RewardInfo value) {
          if (rewardsBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureRewardsIsMutable();
            rewards_.set(index, value);
            onChanged();
          } else {
            rewardsBuilder_.setMessage(index, value);
          }
          return this;
        }
        /**
         * <code>repeated .Common.RewardInfo rewards = 2;</code>
         */
        public Builder setRewards(
            int index, com.znl.proto.Common.RewardInfo.Builder builderForValue) {
          if (rewardsBuilder_ == null) {
            ensureRewardsIsMutable();
            rewards_.set(index, builderForValue.build());
            onChanged();
          } else {
            rewardsBuilder_.setMessage(index, builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .Common.RewardInfo rewards = 2;</code>
         */
        public Builder addRewards(com.znl.proto.Common.RewardInfo value) {
          if (rewardsBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureRewardsIsMutable();
            rewards_.add(value);
            onChanged();
          } else {
            rewardsBuilder_.addMessage(value);
          }
          return this;
        }
        /**
         * <code>repeated .Common.RewardInfo rewards = 2;</code>
         */
        public Builder addRewards(
            int index, com.znl.proto.Common.RewardInfo value) {
          if (rewardsBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureRewardsIsMutable();
            rewards_.add(index, value);
            onChanged();
          } else {
            rewardsBuilder_.addMessage(index, value);
          }
          return this;
        }
        /**
         * <code>repeated .Common.RewardInfo rewards = 2;</code>
         */
        public Builder addRewards(
            com.znl.proto.Common.RewardInfo.Builder builderForValue) {
          if (rewardsBuilder_ == null) {
            ensureRewardsIsMutable();
            rewards_.add(builderForValue.build());
            onChanged();
          } else {
            rewardsBuilder_.addMessage(builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .Common.RewardInfo rewards = 2;</code>
         */
        public Builder addRewards(
            int index, com.znl.proto.Common.RewardInfo.Builder builderForValue) {
          if (rewardsBuilder_ == null) {
            ensureRewardsIsMutable();
            rewards_.add(index, builderForValue.build());
            onChanged();
          } else {
            rewardsBuilder_.addMessage(index, builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .Common.RewardInfo rewards = 2;</code>
         */
        public Builder addAllRewards(
            java.lang.Iterable<? extends com.znl.proto.Common.RewardInfo> values) {
          if (rewardsBuilder_ == null) {
            ensureRewardsIsMutable();
            super.addAll(values, rewards_);
            onChanged();
          } else {
            rewardsBuilder_.addAllMessages(values);
          }
          return this;
        }
        /**
         * <code>repeated .Common.RewardInfo rewards = 2;</code>
         */
        public Builder clearRewards() {
          if (rewardsBuilder_ == null) {
            rewards_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000002);
            onChanged();
          } else {
            rewardsBuilder_.clear();
          }
          return this;
        }
        /**
         * <code>repeated .Common.RewardInfo rewards = 2;</code>
         */
        public Builder removeRewards(int index) {
          if (rewardsBuilder_ == null) {
            ensureRewardsIsMutable();
            rewards_.remove(index);
            onChanged();
          } else {
            rewardsBuilder_.remove(index);
          }
          return this;
        }
        /**
         * <code>repeated .Common.RewardInfo rewards = 2;</code>
         */
        public com.znl.proto.Common.RewardInfo.Builder getRewardsBuilder(
            int index) {
          return getRewardsFieldBuilder().getBuilder(index);
        }
        /**
         * <code>repeated .Common.RewardInfo rewards = 2;</code>
         */
        public com.znl.proto.Common.RewardInfoOrBuilder getRewardsOrBuilder(
            int index) {
          if (rewardsBuilder_ == null) {
            return rewards_.get(index);  } else {
            return rewardsBuilder_.getMessageOrBuilder(index);
          }
        }
        /**
         * <code>repeated .Common.RewardInfo rewards = 2;</code>
         */
        public java.util.List<? extends com.znl.proto.Common.RewardInfoOrBuilder> 
             getRewardsOrBuilderList() {
          if (rewardsBuilder_ != null) {
            return rewardsBuilder_.getMessageOrBuilderList();
          } else {
            return java.util.Collections.unmodifiableList(rewards_);
          }
        }
        /**
         * <code>repeated .Common.RewardInfo rewards = 2;</code>
         */
        public com.znl.proto.Common.RewardInfo.Builder addRewardsBuilder() {
          return getRewardsFieldBuilder().addBuilder(
              com.znl.proto.Common.RewardInfo.getDefaultInstance());
        }
        /**
         * <code>repeated .Common.RewardInfo rewards = 2;</code>
         */
        public com.znl.proto.Common.RewardInfo.Builder addRewardsBuilder(
            int index) {
          return getRewardsFieldBuilder().addBuilder(
              index, com.znl.proto.Common.RewardInfo.getDefaultInstance());
        }
        /**
         * <code>repeated .Common.RewardInfo rewards = 2;</code>
         */
        public java.util.List<com.znl.proto.Common.RewardInfo.Builder> 
             getRewardsBuilderList() {
          return getRewardsFieldBuilder().getBuilderList();
        }
        private com.google.protobuf.RepeatedFieldBuilder<
            com.znl.proto.Common.RewardInfo, com.znl.proto.Common.RewardInfo.Builder, com.znl.proto.Common.RewardInfoOrBuilder> 
            getRewardsFieldBuilder() {
          if (rewardsBuilder_ == null) {
            rewardsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
                com.znl.proto.Common.RewardInfo, com.znl.proto.Common.RewardInfo.Builder, com.znl.proto.Common.RewardInfoOrBuilder>(
                    rewards_,
                    ((bitField0_ & 0x00000002) == 0x00000002),
                    getParentForChildren(),
                    isClean());
            rewards_ = null;
          }
          return rewardsBuilder_;
        }

        // @@protoc_insertion_point(builder_scope:M24.M240000.S2C)
      }

      static {
        defaultInstance = new S2C(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:M24.M240000.S2C)
    }

    public interface C2SOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required string cdkey = 1;
      /**
       * <code>required string cdkey = 1;</code>
       */
      boolean hasCdkey();
      /**
       * <code>required string cdkey = 1;</code>
       */
      java.lang.String getCdkey();
      /**
       * <code>required string cdkey = 1;</code>
       */
      com.google.protobuf.ByteString
          getCdkeyBytes();
    }
    /**
     * Protobuf type {@code M24.M240000.C2S}
     */
    public static final class C2S extends
        com.google.protobuf.GeneratedMessage
        implements C2SOrBuilder {
      // Use C2S.newBuilder() to construct.
      private C2S(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private C2S(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final C2S defaultInstance;
      public static C2S getDefaultInstance() {
        return defaultInstance;
      }

      public C2S getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private C2S(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                cdkey_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.znl.proto.M24.internal_static_M24_M240000_C2S_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.znl.proto.M24.internal_static_M24_M240000_C2S_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.znl.proto.M24.M240000.C2S.class, com.znl.proto.M24.M240000.C2S.Builder.class);
      }

      public static com.google.protobuf.Parser<C2S> PARSER =
          new com.google.protobuf.AbstractParser<C2S>() {
        public C2S parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new C2S(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<C2S> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required string cdkey = 1;
      public static final int CDKEY_FIELD_NUMBER = 1;
      private java.lang.Object cdkey_;
      /**
       * <code>required string cdkey = 1;</code>
       */
      public boolean hasCdkey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string cdkey = 1;</code>
       */
      public java.lang.String getCdkey() {
        java.lang.Object ref = cdkey_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            cdkey_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string cdkey = 1;</code>
       */
      public com.google.protobuf.ByteString
          getCdkeyBytes() {
        java.lang.Object ref = cdkey_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cdkey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        cdkey_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasCdkey()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getCdkeyBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getCdkeyBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.znl.proto.M24.M240000.C2S parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.znl.proto.M24.M240000.C2S parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.znl.proto.M24.M240000.C2S parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.znl.proto.M24.M240000.C2S parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.znl.proto.M24.M240000.C2S parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.znl.proto.M24.M240000.C2S parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.znl.proto.M24.M240000.C2S parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.znl.proto.M24.M240000.C2S parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.znl.proto.M24.M240000.C2S parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.znl.proto.M24.M240000.C2S parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.znl.proto.M24.M240000.C2S prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code M24.M240000.C2S}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.znl.proto.M24.M240000.C2SOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.znl.proto.M24.internal_static_M24_M240000_C2S_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.znl.proto.M24.internal_static_M24_M240000_C2S_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.znl.proto.M24.M240000.C2S.class, com.znl.proto.M24.M240000.C2S.Builder.class);
        }

        // Construct using com.znl.proto.M24.M240000.C2S.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          cdkey_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.znl.proto.M24.internal_static_M24_M240000_C2S_descriptor;
        }

        public com.znl.proto.M24.M240000.C2S getDefaultInstanceForType() {
          return com.znl.proto.M24.M240000.C2S.getDefaultInstance();
        }

        public com.znl.proto.M24.M240000.C2S build() {
          com.znl.proto.M24.M240000.C2S result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.znl.proto.M24.M240000.C2S buildPartial() {
          com.znl.proto.M24.M240000.C2S result = new com.znl.proto.M24.M240000.C2S(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.cdkey_ = cdkey_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.znl.proto.M24.M240000.C2S) {
            return mergeFrom((com.znl.proto.M24.M240000.C2S)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.znl.proto.M24.M240000.C2S other) {
          if (other == com.znl.proto.M24.M240000.C2S.getDefaultInstance()) return this;
          if (other.hasCdkey()) {
            bitField0_ |= 0x00000001;
            cdkey_ = other.cdkey_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasCdkey()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.znl.proto.M24.M240000.C2S parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.znl.proto.M24.M240000.C2S) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required string cdkey = 1;
        private java.lang.Object cdkey_ = "";
        /**
         * <code>required string cdkey = 1;</code>
         */
        public boolean hasCdkey() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string cdkey = 1;</code>
         */
        public java.lang.String getCdkey() {
          java.lang.Object ref = cdkey_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            cdkey_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string cdkey = 1;</code>
         */
        public com.google.protobuf.ByteString
            getCdkeyBytes() {
          java.lang.Object ref = cdkey_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            cdkey_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string cdkey = 1;</code>
         */
        public Builder setCdkey(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          cdkey_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string cdkey = 1;</code>
         */
        public Builder clearCdkey() {
          bitField0_ = (bitField0_ & ~0x00000001);
          cdkey_ = getDefaultInstance().getCdkey();
          onChanged();
          return this;
        }
        /**
         * <code>required string cdkey = 1;</code>
         */
        public Builder setCdkeyBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          cdkey_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:M24.M240000.C2S)
      }

      static {
        defaultInstance = new C2S(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:M24.M240000.C2S)
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.znl.proto.M24.M240000 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.znl.proto.M24.M240000 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.znl.proto.M24.M240000 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.znl.proto.M24.M240000 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.znl.proto.M24.M240000 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.znl.proto.M24.M240000 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.znl.proto.M24.M240000 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.znl.proto.M24.M240000 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.znl.proto.M24.M240000 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.znl.proto.M24.M240000 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.znl.proto.M24.M240000 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code M24.M240000}
     *
     * <pre>
     *获取活动列表
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.znl.proto.M24.M240000OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.znl.proto.M24.internal_static_M24_M240000_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.znl.proto.M24.internal_static_M24_M240000_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.znl.proto.M24.M240000.class, com.znl.proto.M24.M240000.Builder.class);
      }

      // Construct using com.znl.proto.M24.M240000.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.znl.proto.M24.internal_static_M24_M240000_descriptor;
      }

      public com.znl.proto.M24.M240000 getDefaultInstanceForType() {
        return com.znl.proto.M24.M240000.getDefaultInstance();
      }

      public com.znl.proto.M24.M240000 build() {
        com.znl.proto.M24.M240000 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.znl.proto.M24.M240000 buildPartial() {
        com.znl.proto.M24.M240000 result = new com.znl.proto.M24.M240000(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.znl.proto.M24.M240000) {
          return mergeFrom((com.znl.proto.M24.M240000)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.znl.proto.M24.M240000 other) {
        if (other == com.znl.proto.M24.M240000.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.znl.proto.M24.M240000 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.znl.proto.M24.M240000) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:M24.M240000)
    }

    static {
      defaultInstance = new M240000(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:M24.M240000)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_M24_M240000_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_M24_M240000_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_M24_M240000_S2C_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_M24_M240000_S2C_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_M24_M240000_C2S_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_M24_M240000_C2S_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tM24.proto\022\003M24\032\014Common.proto\"W\n\007M24000" +
      "0\0326\n\003S2C\022\n\n\002rs\030\001 \002(\005\022#\n\007rewards\030\002 \003(\0132\022." +
      "Common.RewardInfo\032\024\n\003C2S\022\r\n\005cdkey\030\001 \002(\tB" +
      "\024\n\rcom.znl.protoB\003M24"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_M24_M240000_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_M24_M240000_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_M24_M240000_descriptor,
              new java.lang.String[] { });
          internal_static_M24_M240000_S2C_descriptor =
            internal_static_M24_M240000_descriptor.getNestedTypes().get(0);
          internal_static_M24_M240000_S2C_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_M24_M240000_S2C_descriptor,
              new java.lang.String[] { "Rs", "Rewards", });
          internal_static_M24_M240000_C2S_descriptor =
            internal_static_M24_M240000_descriptor.getNestedTypes().get(1);
          internal_static_M24_M240000_C2S_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_M24_M240000_C2S_descriptor,
              new java.lang.String[] { "Cdkey", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.znl.proto.Common.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
