// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: M25.proto

package com.znl.proto;

public final class M25 {
  private M25() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface M250000OrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code M25.M250000}
   *
   * <pre>
   *分享功能
   * </pre>
   */
  public static final class M250000 extends
      com.google.protobuf.GeneratedMessage
      implements M250000OrBuilder {
    // Use M250000.newBuilder() to construct.
    private M250000(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private M250000(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final M250000 defaultInstance;
    public static M250000 getDefaultInstance() {
      return defaultInstance;
    }

    public M250000 getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private M250000(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.znl.proto.M25.internal_static_M25_M250000_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.znl.proto.M25.internal_static_M25_M250000_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.znl.proto.M25.M250000.class, com.znl.proto.M25.M250000.Builder.class);
    }

    public static com.google.protobuf.Parser<M250000> PARSER =
        new com.google.protobuf.AbstractParser<M250000>() {
      public M250000 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new M250000(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<M250000> getParserForType() {
      return PARSER;
    }

    public interface S2COrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required int32 rs = 1;
      /**
       * <code>required int32 rs = 1;</code>
       */
      boolean hasRs();
      /**
       * <code>required int32 rs = 1;</code>
       */
      int getRs();

      // optional int32 type = 2;
      /**
       * <code>optional int32 type = 2;</code>
       *
       * <pre>
       *1：佣兵分享，2：竞技场战报分享，3：野外战报分享，4：系统公告 ，5军团招募
       * </pre>
       */
      boolean hasType();
      /**
       * <code>optional int32 type = 2;</code>
       *
       * <pre>
       *1：佣兵分享，2：竞技场战报分享，3：野外战报分享，4：系统公告 ，5军团招募
       * </pre>
       */
      int getType();

      // optional .Common.SoldierInfo soldierInfo = 3;
      /**
       * <code>optional .Common.SoldierInfo soldierInfo = 3;</code>
       */
      boolean hasSoldierInfo();
      /**
       * <code>optional .Common.SoldierInfo soldierInfo = 3;</code>
       */
      com.znl.proto.Common.SoldierInfo getSoldierInfo();
      /**
       * <code>optional .Common.SoldierInfo soldierInfo = 3;</code>
       */
      com.znl.proto.Common.SoldierInfoOrBuilder getSoldierInfoOrBuilder();

      // optional .M20.PerDetailInfos areanInfo = 4;
      /**
       * <code>optional .M20.PerDetailInfos areanInfo = 4;</code>
       */
      boolean hasAreanInfo();
      /**
       * <code>optional .M20.PerDetailInfos areanInfo = 4;</code>
       */
      com.znl.proto.M20.PerDetailInfos getAreanInfo();
      /**
       * <code>optional .M20.PerDetailInfos areanInfo = 4;</code>
       */
      com.znl.proto.M20.PerDetailInfosOrBuilder getAreanInfoOrBuilder();

      // optional .M16.MailDetalInfo reportInfo = 5;
      /**
       * <code>optional .M16.MailDetalInfo reportInfo = 5;</code>
       */
      boolean hasReportInfo();
      /**
       * <code>optional .M16.MailDetalInfo reportInfo = 5;</code>
       */
      com.znl.proto.M16.MailDetalInfo getReportInfo();
      /**
       * <code>optional .M16.MailDetalInfo reportInfo = 5;</code>
       */
      com.znl.proto.M16.MailDetalInfoOrBuilder getReportInfoOrBuilder();

      // optional .M14.ChatInfo chat = 6;
      /**
       * <code>optional .M14.ChatInfo chat = 6;</code>
       */
      boolean hasChat();
      /**
       * <code>optional .M14.ChatInfo chat = 6;</code>
       */
      com.znl.proto.M14.ChatInfo getChat();
      /**
       * <code>optional .M14.ChatInfo chat = 6;</code>
       */
      com.znl.proto.M14.ChatInfoOrBuilder getChatOrBuilder();

      // optional fixed64 id = 7;
      /**
       * <code>optional fixed64 id = 7;</code>
       */
      boolean hasId();
      /**
       * <code>optional fixed64 id = 7;</code>
       */
      long getId();

      // optional int32 typeId = 8;
      /**
       * <code>optional int32 typeId = 8;</code>
       *
       * <pre>
       *佣兵分享的时候传typeId，系统公告时传公告id
       * </pre>
       */
      boolean hasTypeId();
      /**
       * <code>optional int32 typeId = 8;</code>
       *
       * <pre>
       *佣兵分享的时候传typeId，系统公告时传公告id
       * </pre>
       */
      int getTypeId();

      // optional int32 shareType = 9;
      /**
       * <code>optional int32 shareType = 9;</code>
       *
       * <pre>
       *1:世界分享，2：军团分享
       * </pre>
       */
      boolean hasShareType();
      /**
       * <code>optional int32 shareType = 9;</code>
       *
       * <pre>
       *1:世界分享，2：军团分享
       * </pre>
       */
      int getShareType();
    }
    /**
     * Protobuf type {@code M25.M250000.S2C}
     */
    public static final class S2C extends
        com.google.protobuf.GeneratedMessage
        implements S2COrBuilder {
      // Use S2C.newBuilder() to construct.
      private S2C(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private S2C(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final S2C defaultInstance;
      public static S2C getDefaultInstance() {
        return defaultInstance;
      }

      public S2C getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private S2C(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                rs_ = input.readInt32();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                type_ = input.readInt32();
                break;
              }
              case 26: {
                com.znl.proto.Common.SoldierInfo.Builder subBuilder = null;
                if (((bitField0_ & 0x00000004) == 0x00000004)) {
                  subBuilder = soldierInfo_.toBuilder();
                }
                soldierInfo_ = input.readMessage(com.znl.proto.Common.SoldierInfo.PARSER, extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(soldierInfo_);
                  soldierInfo_ = subBuilder.buildPartial();
                }
                bitField0_ |= 0x00000004;
                break;
              }
              case 34: {
                com.znl.proto.M20.PerDetailInfos.Builder subBuilder = null;
                if (((bitField0_ & 0x00000008) == 0x00000008)) {
                  subBuilder = areanInfo_.toBuilder();
                }
                areanInfo_ = input.readMessage(com.znl.proto.M20.PerDetailInfos.PARSER, extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(areanInfo_);
                  areanInfo_ = subBuilder.buildPartial();
                }
                bitField0_ |= 0x00000008;
                break;
              }
              case 42: {
                com.znl.proto.M16.MailDetalInfo.Builder subBuilder = null;
                if (((bitField0_ & 0x00000010) == 0x00000010)) {
                  subBuilder = reportInfo_.toBuilder();
                }
                reportInfo_ = input.readMessage(com.znl.proto.M16.MailDetalInfo.PARSER, extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(reportInfo_);
                  reportInfo_ = subBuilder.buildPartial();
                }
                bitField0_ |= 0x00000010;
                break;
              }
              case 50: {
                com.znl.proto.M14.ChatInfo.Builder subBuilder = null;
                if (((bitField0_ & 0x00000020) == 0x00000020)) {
                  subBuilder = chat_.toBuilder();
                }
                chat_ = input.readMessage(com.znl.proto.M14.ChatInfo.PARSER, extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(chat_);
                  chat_ = subBuilder.buildPartial();
                }
                bitField0_ |= 0x00000020;
                break;
              }
              case 57: {
                bitField0_ |= 0x00000040;
                id_ = input.readFixed64();
                break;
              }
              case 64: {
                bitField0_ |= 0x00000080;
                typeId_ = input.readInt32();
                break;
              }
              case 72: {
                bitField0_ |= 0x00000100;
                shareType_ = input.readInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.znl.proto.M25.internal_static_M25_M250000_S2C_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.znl.proto.M25.internal_static_M25_M250000_S2C_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.znl.proto.M25.M250000.S2C.class, com.znl.proto.M25.M250000.S2C.Builder.class);
      }

      public static com.google.protobuf.Parser<S2C> PARSER =
          new com.google.protobuf.AbstractParser<S2C>() {
        public S2C parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new S2C(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<S2C> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required int32 rs = 1;
      public static final int RS_FIELD_NUMBER = 1;
      private int rs_;
      /**
       * <code>required int32 rs = 1;</code>
       */
      public boolean hasRs() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 rs = 1;</code>
       */
      public int getRs() {
        return rs_;
      }

      // optional int32 type = 2;
      public static final int TYPE_FIELD_NUMBER = 2;
      private int type_;
      /**
       * <code>optional int32 type = 2;</code>
       *
       * <pre>
       *1：佣兵分享，2：竞技场战报分享，3：野外战报分享，4：系统公告 ，5军团招募
       * </pre>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 type = 2;</code>
       *
       * <pre>
       *1：佣兵分享，2：竞技场战报分享，3：野外战报分享，4：系统公告 ，5军团招募
       * </pre>
       */
      public int getType() {
        return type_;
      }

      // optional .Common.SoldierInfo soldierInfo = 3;
      public static final int SOLDIERINFO_FIELD_NUMBER = 3;
      private com.znl.proto.Common.SoldierInfo soldierInfo_;
      /**
       * <code>optional .Common.SoldierInfo soldierInfo = 3;</code>
       */
      public boolean hasSoldierInfo() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .Common.SoldierInfo soldierInfo = 3;</code>
       */
      public com.znl.proto.Common.SoldierInfo getSoldierInfo() {
        return soldierInfo_;
      }
      /**
       * <code>optional .Common.SoldierInfo soldierInfo = 3;</code>
       */
      public com.znl.proto.Common.SoldierInfoOrBuilder getSoldierInfoOrBuilder() {
        return soldierInfo_;
      }

      // optional .M20.PerDetailInfos areanInfo = 4;
      public static final int AREANINFO_FIELD_NUMBER = 4;
      private com.znl.proto.M20.PerDetailInfos areanInfo_;
      /**
       * <code>optional .M20.PerDetailInfos areanInfo = 4;</code>
       */
      public boolean hasAreanInfo() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .M20.PerDetailInfos areanInfo = 4;</code>
       */
      public com.znl.proto.M20.PerDetailInfos getAreanInfo() {
        return areanInfo_;
      }
      /**
       * <code>optional .M20.PerDetailInfos areanInfo = 4;</code>
       */
      public com.znl.proto.M20.PerDetailInfosOrBuilder getAreanInfoOrBuilder() {
        return areanInfo_;
      }

      // optional .M16.MailDetalInfo reportInfo = 5;
      public static final int REPORTINFO_FIELD_NUMBER = 5;
      private com.znl.proto.M16.MailDetalInfo reportInfo_;
      /**
       * <code>optional .M16.MailDetalInfo reportInfo = 5;</code>
       */
      public boolean hasReportInfo() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .M16.MailDetalInfo reportInfo = 5;</code>
       */
      public com.znl.proto.M16.MailDetalInfo getReportInfo() {
        return reportInfo_;
      }
      /**
       * <code>optional .M16.MailDetalInfo reportInfo = 5;</code>
       */
      public com.znl.proto.M16.MailDetalInfoOrBuilder getReportInfoOrBuilder() {
        return reportInfo_;
      }

      // optional .M14.ChatInfo chat = 6;
      public static final int CHAT_FIELD_NUMBER = 6;
      private com.znl.proto.M14.ChatInfo chat_;
      /**
       * <code>optional .M14.ChatInfo chat = 6;</code>
       */
      public boolean hasChat() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional .M14.ChatInfo chat = 6;</code>
       */
      public com.znl.proto.M14.ChatInfo getChat() {
        return chat_;
      }
      /**
       * <code>optional .M14.ChatInfo chat = 6;</code>
       */
      public com.znl.proto.M14.ChatInfoOrBuilder getChatOrBuilder() {
        return chat_;
      }

      // optional fixed64 id = 7;
      public static final int ID_FIELD_NUMBER = 7;
      private long id_;
      /**
       * <code>optional fixed64 id = 7;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional fixed64 id = 7;</code>
       */
      public long getId() {
        return id_;
      }

      // optional int32 typeId = 8;
      public static final int TYPEID_FIELD_NUMBER = 8;
      private int typeId_;
      /**
       * <code>optional int32 typeId = 8;</code>
       *
       * <pre>
       *佣兵分享的时候传typeId，系统公告时传公告id
       * </pre>
       */
      public boolean hasTypeId() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional int32 typeId = 8;</code>
       *
       * <pre>
       *佣兵分享的时候传typeId，系统公告时传公告id
       * </pre>
       */
      public int getTypeId() {
        return typeId_;
      }

      // optional int32 shareType = 9;
      public static final int SHARETYPE_FIELD_NUMBER = 9;
      private int shareType_;
      /**
       * <code>optional int32 shareType = 9;</code>
       *
       * <pre>
       *1:世界分享，2：军团分享
       * </pre>
       */
      public boolean hasShareType() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional int32 shareType = 9;</code>
       *
       * <pre>
       *1:世界分享，2：军团分享
       * </pre>
       */
      public int getShareType() {
        return shareType_;
      }

      private void initFields() {
        rs_ = 0;
        type_ = 0;
        soldierInfo_ = com.znl.proto.Common.SoldierInfo.getDefaultInstance();
        areanInfo_ = com.znl.proto.M20.PerDetailInfos.getDefaultInstance();
        reportInfo_ = com.znl.proto.M16.MailDetalInfo.getDefaultInstance();
        chat_ = com.znl.proto.M14.ChatInfo.getDefaultInstance();
        id_ = 0L;
        typeId_ = 0;
        shareType_ = 0;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasRs()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (hasSoldierInfo()) {
          if (!getSoldierInfo().isInitialized()) {
            memoizedIsInitialized = 0;
            return false;
          }
        }
        if (hasAreanInfo()) {
          if (!getAreanInfo().isInitialized()) {
            memoizedIsInitialized = 0;
            return false;
          }
        }
        if (hasReportInfo()) {
          if (!getReportInfo().isInitialized()) {
            memoizedIsInitialized = 0;
            return false;
          }
        }
        if (hasChat()) {
          if (!getChat().isInitialized()) {
            memoizedIsInitialized = 0;
            return false;
          }
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, rs_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeInt32(2, type_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeMessage(3, soldierInfo_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeMessage(4, areanInfo_);
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          output.writeMessage(5, reportInfo_);
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          output.writeMessage(6, chat_);
        }
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          output.writeFixed64(7, id_);
        }
        if (((bitField0_ & 0x00000080) == 0x00000080)) {
          output.writeInt32(8, typeId_);
        }
        if (((bitField0_ & 0x00000100) == 0x00000100)) {
          output.writeInt32(9, shareType_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, rs_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, type_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(3, soldierInfo_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(4, areanInfo_);
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(5, reportInfo_);
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(6, chat_);
        }
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          size += com.google.protobuf.CodedOutputStream
            .computeFixed64Size(7, id_);
        }
        if (((bitField0_ & 0x00000080) == 0x00000080)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(8, typeId_);
        }
        if (((bitField0_ & 0x00000100) == 0x00000100)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(9, shareType_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.znl.proto.M25.M250000.S2C parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.znl.proto.M25.M250000.S2C parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.znl.proto.M25.M250000.S2C parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.znl.proto.M25.M250000.S2C parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.znl.proto.M25.M250000.S2C parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.znl.proto.M25.M250000.S2C parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.znl.proto.M25.M250000.S2C parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.znl.proto.M25.M250000.S2C parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.znl.proto.M25.M250000.S2C parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.znl.proto.M25.M250000.S2C parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.znl.proto.M25.M250000.S2C prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code M25.M250000.S2C}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.znl.proto.M25.M250000.S2COrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.znl.proto.M25.internal_static_M25_M250000_S2C_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.znl.proto.M25.internal_static_M25_M250000_S2C_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.znl.proto.M25.M250000.S2C.class, com.znl.proto.M25.M250000.S2C.Builder.class);
        }

        // Construct using com.znl.proto.M25.M250000.S2C.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
            getSoldierInfoFieldBuilder();
            getAreanInfoFieldBuilder();
            getReportInfoFieldBuilder();
            getChatFieldBuilder();
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          rs_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          type_ = 0;
          bitField0_ = (bitField0_ & ~0x00000002);
          if (soldierInfoBuilder_ == null) {
            soldierInfo_ = com.znl.proto.Common.SoldierInfo.getDefaultInstance();
          } else {
            soldierInfoBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000004);
          if (areanInfoBuilder_ == null) {
            areanInfo_ = com.znl.proto.M20.PerDetailInfos.getDefaultInstance();
          } else {
            areanInfoBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000008);
          if (reportInfoBuilder_ == null) {
            reportInfo_ = com.znl.proto.M16.MailDetalInfo.getDefaultInstance();
          } else {
            reportInfoBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000010);
          if (chatBuilder_ == null) {
            chat_ = com.znl.proto.M14.ChatInfo.getDefaultInstance();
          } else {
            chatBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000020);
          id_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000040);
          typeId_ = 0;
          bitField0_ = (bitField0_ & ~0x00000080);
          shareType_ = 0;
          bitField0_ = (bitField0_ & ~0x00000100);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.znl.proto.M25.internal_static_M25_M250000_S2C_descriptor;
        }

        public com.znl.proto.M25.M250000.S2C getDefaultInstanceForType() {
          return com.znl.proto.M25.M250000.S2C.getDefaultInstance();
        }

        public com.znl.proto.M25.M250000.S2C build() {
          com.znl.proto.M25.M250000.S2C result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.znl.proto.M25.M250000.S2C buildPartial() {
          com.znl.proto.M25.M250000.S2C result = new com.znl.proto.M25.M250000.S2C(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.rs_ = rs_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.type_ = type_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          if (soldierInfoBuilder_ == null) {
            result.soldierInfo_ = soldierInfo_;
          } else {
            result.soldierInfo_ = soldierInfoBuilder_.build();
          }
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          if (areanInfoBuilder_ == null) {
            result.areanInfo_ = areanInfo_;
          } else {
            result.areanInfo_ = areanInfoBuilder_.build();
          }
          if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
            to_bitField0_ |= 0x00000010;
          }
          if (reportInfoBuilder_ == null) {
            result.reportInfo_ = reportInfo_;
          } else {
            result.reportInfo_ = reportInfoBuilder_.build();
          }
          if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
            to_bitField0_ |= 0x00000020;
          }
          if (chatBuilder_ == null) {
            result.chat_ = chat_;
          } else {
            result.chat_ = chatBuilder_.build();
          }
          if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
            to_bitField0_ |= 0x00000040;
          }
          result.id_ = id_;
          if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
            to_bitField0_ |= 0x00000080;
          }
          result.typeId_ = typeId_;
          if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
            to_bitField0_ |= 0x00000100;
          }
          result.shareType_ = shareType_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.znl.proto.M25.M250000.S2C) {
            return mergeFrom((com.znl.proto.M25.M250000.S2C)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.znl.proto.M25.M250000.S2C other) {
          if (other == com.znl.proto.M25.M250000.S2C.getDefaultInstance()) return this;
          if (other.hasRs()) {
            setRs(other.getRs());
          }
          if (other.hasType()) {
            setType(other.getType());
          }
          if (other.hasSoldierInfo()) {
            mergeSoldierInfo(other.getSoldierInfo());
          }
          if (other.hasAreanInfo()) {
            mergeAreanInfo(other.getAreanInfo());
          }
          if (other.hasReportInfo()) {
            mergeReportInfo(other.getReportInfo());
          }
          if (other.hasChat()) {
            mergeChat(other.getChat());
          }
          if (other.hasId()) {
            setId(other.getId());
          }
          if (other.hasTypeId()) {
            setTypeId(other.getTypeId());
          }
          if (other.hasShareType()) {
            setShareType(other.getShareType());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasRs()) {
            
            return false;
          }
          if (hasSoldierInfo()) {
            if (!getSoldierInfo().isInitialized()) {
              
              return false;
            }
          }
          if (hasAreanInfo()) {
            if (!getAreanInfo().isInitialized()) {
              
              return false;
            }
          }
          if (hasReportInfo()) {
            if (!getReportInfo().isInitialized()) {
              
              return false;
            }
          }
          if (hasChat()) {
            if (!getChat().isInitialized()) {
              
              return false;
            }
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.znl.proto.M25.M250000.S2C parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.znl.proto.M25.M250000.S2C) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required int32 rs = 1;
        private int rs_ ;
        /**
         * <code>required int32 rs = 1;</code>
         */
        public boolean hasRs() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required int32 rs = 1;</code>
         */
        public int getRs() {
          return rs_;
        }
        /**
         * <code>required int32 rs = 1;</code>
         */
        public Builder setRs(int value) {
          bitField0_ |= 0x00000001;
          rs_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 rs = 1;</code>
         */
        public Builder clearRs() {
          bitField0_ = (bitField0_ & ~0x00000001);
          rs_ = 0;
          onChanged();
          return this;
        }

        // optional int32 type = 2;
        private int type_ ;
        /**
         * <code>optional int32 type = 2;</code>
         *
         * <pre>
         *1：佣兵分享，2：竞技场战报分享，3：野外战报分享，4：系统公告 ，5军团招募
         * </pre>
         */
        public boolean hasType() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional int32 type = 2;</code>
         *
         * <pre>
         *1：佣兵分享，2：竞技场战报分享，3：野外战报分享，4：系统公告 ，5军团招募
         * </pre>
         */
        public int getType() {
          return type_;
        }
        /**
         * <code>optional int32 type = 2;</code>
         *
         * <pre>
         *1：佣兵分享，2：竞技场战报分享，3：野外战报分享，4：系统公告 ，5军团招募
         * </pre>
         */
        public Builder setType(int value) {
          bitField0_ |= 0x00000002;
          type_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 type = 2;</code>
         *
         * <pre>
         *1：佣兵分享，2：竞技场战报分享，3：野外战报分享，4：系统公告 ，5军团招募
         * </pre>
         */
        public Builder clearType() {
          bitField0_ = (bitField0_ & ~0x00000002);
          type_ = 0;
          onChanged();
          return this;
        }

        // optional .Common.SoldierInfo soldierInfo = 3;
        private com.znl.proto.Common.SoldierInfo soldierInfo_ = com.znl.proto.Common.SoldierInfo.getDefaultInstance();
        private com.google.protobuf.SingleFieldBuilder<
            com.znl.proto.Common.SoldierInfo, com.znl.proto.Common.SoldierInfo.Builder, com.znl.proto.Common.SoldierInfoOrBuilder> soldierInfoBuilder_;
        /**
         * <code>optional .Common.SoldierInfo soldierInfo = 3;</code>
         */
        public boolean hasSoldierInfo() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional .Common.SoldierInfo soldierInfo = 3;</code>
         */
        public com.znl.proto.Common.SoldierInfo getSoldierInfo() {
          if (soldierInfoBuilder_ == null) {
            return soldierInfo_;
          } else {
            return soldierInfoBuilder_.getMessage();
          }
        }
        /**
         * <code>optional .Common.SoldierInfo soldierInfo = 3;</code>
         */
        public Builder setSoldierInfo(com.znl.proto.Common.SoldierInfo value) {
          if (soldierInfoBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            soldierInfo_ = value;
            onChanged();
          } else {
            soldierInfoBuilder_.setMessage(value);
          }
          bitField0_ |= 0x00000004;
          return this;
        }
        /**
         * <code>optional .Common.SoldierInfo soldierInfo = 3;</code>
         */
        public Builder setSoldierInfo(
            com.znl.proto.Common.SoldierInfo.Builder builderForValue) {
          if (soldierInfoBuilder_ == null) {
            soldierInfo_ = builderForValue.build();
            onChanged();
          } else {
            soldierInfoBuilder_.setMessage(builderForValue.build());
          }
          bitField0_ |= 0x00000004;
          return this;
        }
        /**
         * <code>optional .Common.SoldierInfo soldierInfo = 3;</code>
         */
        public Builder mergeSoldierInfo(com.znl.proto.Common.SoldierInfo value) {
          if (soldierInfoBuilder_ == null) {
            if (((bitField0_ & 0x00000004) == 0x00000004) &&
                soldierInfo_ != com.znl.proto.Common.SoldierInfo.getDefaultInstance()) {
              soldierInfo_ =
                com.znl.proto.Common.SoldierInfo.newBuilder(soldierInfo_).mergeFrom(value).buildPartial();
            } else {
              soldierInfo_ = value;
            }
            onChanged();
          } else {
            soldierInfoBuilder_.mergeFrom(value);
          }
          bitField0_ |= 0x00000004;
          return this;
        }
        /**
         * <code>optional .Common.SoldierInfo soldierInfo = 3;</code>
         */
        public Builder clearSoldierInfo() {
          if (soldierInfoBuilder_ == null) {
            soldierInfo_ = com.znl.proto.Common.SoldierInfo.getDefaultInstance();
            onChanged();
          } else {
            soldierInfoBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }
        /**
         * <code>optional .Common.SoldierInfo soldierInfo = 3;</code>
         */
        public com.znl.proto.Common.SoldierInfo.Builder getSoldierInfoBuilder() {
          bitField0_ |= 0x00000004;
          onChanged();
          return getSoldierInfoFieldBuilder().getBuilder();
        }
        /**
         * <code>optional .Common.SoldierInfo soldierInfo = 3;</code>
         */
        public com.znl.proto.Common.SoldierInfoOrBuilder getSoldierInfoOrBuilder() {
          if (soldierInfoBuilder_ != null) {
            return soldierInfoBuilder_.getMessageOrBuilder();
          } else {
            return soldierInfo_;
          }
        }
        /**
         * <code>optional .Common.SoldierInfo soldierInfo = 3;</code>
         */
        private com.google.protobuf.SingleFieldBuilder<
            com.znl.proto.Common.SoldierInfo, com.znl.proto.Common.SoldierInfo.Builder, com.znl.proto.Common.SoldierInfoOrBuilder> 
            getSoldierInfoFieldBuilder() {
          if (soldierInfoBuilder_ == null) {
            soldierInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                com.znl.proto.Common.SoldierInfo, com.znl.proto.Common.SoldierInfo.Builder, com.znl.proto.Common.SoldierInfoOrBuilder>(
                    soldierInfo_,
                    getParentForChildren(),
                    isClean());
            soldierInfo_ = null;
          }
          return soldierInfoBuilder_;
        }

        // optional .M20.PerDetailInfos areanInfo = 4;
        private com.znl.proto.M20.PerDetailInfos areanInfo_ = com.znl.proto.M20.PerDetailInfos.getDefaultInstance();
        private com.google.protobuf.SingleFieldBuilder<
            com.znl.proto.M20.PerDetailInfos, com.znl.proto.M20.PerDetailInfos.Builder, com.znl.proto.M20.PerDetailInfosOrBuilder> areanInfoBuilder_;
        /**
         * <code>optional .M20.PerDetailInfos areanInfo = 4;</code>
         */
        public boolean hasAreanInfo() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>optional .M20.PerDetailInfos areanInfo = 4;</code>
         */
        public com.znl.proto.M20.PerDetailInfos getAreanInfo() {
          if (areanInfoBuilder_ == null) {
            return areanInfo_;
          } else {
            return areanInfoBuilder_.getMessage();
          }
        }
        /**
         * <code>optional .M20.PerDetailInfos areanInfo = 4;</code>
         */
        public Builder setAreanInfo(com.znl.proto.M20.PerDetailInfos value) {
          if (areanInfoBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            areanInfo_ = value;
            onChanged();
          } else {
            areanInfoBuilder_.setMessage(value);
          }
          bitField0_ |= 0x00000008;
          return this;
        }
        /**
         * <code>optional .M20.PerDetailInfos areanInfo = 4;</code>
         */
        public Builder setAreanInfo(
            com.znl.proto.M20.PerDetailInfos.Builder builderForValue) {
          if (areanInfoBuilder_ == null) {
            areanInfo_ = builderForValue.build();
            onChanged();
          } else {
            areanInfoBuilder_.setMessage(builderForValue.build());
          }
          bitField0_ |= 0x00000008;
          return this;
        }
        /**
         * <code>optional .M20.PerDetailInfos areanInfo = 4;</code>
         */
        public Builder mergeAreanInfo(com.znl.proto.M20.PerDetailInfos value) {
          if (areanInfoBuilder_ == null) {
            if (((bitField0_ & 0x00000008) == 0x00000008) &&
                areanInfo_ != com.znl.proto.M20.PerDetailInfos.getDefaultInstance()) {
              areanInfo_ =
                com.znl.proto.M20.PerDetailInfos.newBuilder(areanInfo_).mergeFrom(value).buildPartial();
            } else {
              areanInfo_ = value;
            }
            onChanged();
          } else {
            areanInfoBuilder_.mergeFrom(value);
          }
          bitField0_ |= 0x00000008;
          return this;
        }
        /**
         * <code>optional .M20.PerDetailInfos areanInfo = 4;</code>
         */
        public Builder clearAreanInfo() {
          if (areanInfoBuilder_ == null) {
            areanInfo_ = com.znl.proto.M20.PerDetailInfos.getDefaultInstance();
            onChanged();
          } else {
            areanInfoBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000008);
          return this;
        }
        /**
         * <code>optional .M20.PerDetailInfos areanInfo = 4;</code>
         */
        public com.znl.proto.M20.PerDetailInfos.Builder getAreanInfoBuilder() {
          bitField0_ |= 0x00000008;
          onChanged();
          return getAreanInfoFieldBuilder().getBuilder();
        }
        /**
         * <code>optional .M20.PerDetailInfos areanInfo = 4;</code>
         */
        public com.znl.proto.M20.PerDetailInfosOrBuilder getAreanInfoOrBuilder() {
          if (areanInfoBuilder_ != null) {
            return areanInfoBuilder_.getMessageOrBuilder();
          } else {
            return areanInfo_;
          }
        }
        /**
         * <code>optional .M20.PerDetailInfos areanInfo = 4;</code>
         */
        private com.google.protobuf.SingleFieldBuilder<
            com.znl.proto.M20.PerDetailInfos, com.znl.proto.M20.PerDetailInfos.Builder, com.znl.proto.M20.PerDetailInfosOrBuilder> 
            getAreanInfoFieldBuilder() {
          if (areanInfoBuilder_ == null) {
            areanInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                com.znl.proto.M20.PerDetailInfos, com.znl.proto.M20.PerDetailInfos.Builder, com.znl.proto.M20.PerDetailInfosOrBuilder>(
                    areanInfo_,
                    getParentForChildren(),
                    isClean());
            areanInfo_ = null;
          }
          return areanInfoBuilder_;
        }

        // optional .M16.MailDetalInfo reportInfo = 5;
        private com.znl.proto.M16.MailDetalInfo reportInfo_ = com.znl.proto.M16.MailDetalInfo.getDefaultInstance();
        private com.google.protobuf.SingleFieldBuilder<
            com.znl.proto.M16.MailDetalInfo, com.znl.proto.M16.MailDetalInfo.Builder, com.znl.proto.M16.MailDetalInfoOrBuilder> reportInfoBuilder_;
        /**
         * <code>optional .M16.MailDetalInfo reportInfo = 5;</code>
         */
        public boolean hasReportInfo() {
          return ((bitField0_ & 0x00000010) == 0x00000010);
        }
        /**
         * <code>optional .M16.MailDetalInfo reportInfo = 5;</code>
         */
        public com.znl.proto.M16.MailDetalInfo getReportInfo() {
          if (reportInfoBuilder_ == null) {
            return reportInfo_;
          } else {
            return reportInfoBuilder_.getMessage();
          }
        }
        /**
         * <code>optional .M16.MailDetalInfo reportInfo = 5;</code>
         */
        public Builder setReportInfo(com.znl.proto.M16.MailDetalInfo value) {
          if (reportInfoBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            reportInfo_ = value;
            onChanged();
          } else {
            reportInfoBuilder_.setMessage(value);
          }
          bitField0_ |= 0x00000010;
          return this;
        }
        /**
         * <code>optional .M16.MailDetalInfo reportInfo = 5;</code>
         */
        public Builder setReportInfo(
            com.znl.proto.M16.MailDetalInfo.Builder builderForValue) {
          if (reportInfoBuilder_ == null) {
            reportInfo_ = builderForValue.build();
            onChanged();
          } else {
            reportInfoBuilder_.setMessage(builderForValue.build());
          }
          bitField0_ |= 0x00000010;
          return this;
        }
        /**
         * <code>optional .M16.MailDetalInfo reportInfo = 5;</code>
         */
        public Builder mergeReportInfo(com.znl.proto.M16.MailDetalInfo value) {
          if (reportInfoBuilder_ == null) {
            if (((bitField0_ & 0x00000010) == 0x00000010) &&
                reportInfo_ != com.znl.proto.M16.MailDetalInfo.getDefaultInstance()) {
              reportInfo_ =
                com.znl.proto.M16.MailDetalInfo.newBuilder(reportInfo_).mergeFrom(value).buildPartial();
            } else {
              reportInfo_ = value;
            }
            onChanged();
          } else {
            reportInfoBuilder_.mergeFrom(value);
          }
          bitField0_ |= 0x00000010;
          return this;
        }
        /**
         * <code>optional .M16.MailDetalInfo reportInfo = 5;</code>
         */
        public Builder clearReportInfo() {
          if (reportInfoBuilder_ == null) {
            reportInfo_ = com.znl.proto.M16.MailDetalInfo.getDefaultInstance();
            onChanged();
          } else {
            reportInfoBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000010);
          return this;
        }
        /**
         * <code>optional .M16.MailDetalInfo reportInfo = 5;</code>
         */
        public com.znl.proto.M16.MailDetalInfo.Builder getReportInfoBuilder() {
          bitField0_ |= 0x00000010;
          onChanged();
          return getReportInfoFieldBuilder().getBuilder();
        }
        /**
         * <code>optional .M16.MailDetalInfo reportInfo = 5;</code>
         */
        public com.znl.proto.M16.MailDetalInfoOrBuilder getReportInfoOrBuilder() {
          if (reportInfoBuilder_ != null) {
            return reportInfoBuilder_.getMessageOrBuilder();
          } else {
            return reportInfo_;
          }
        }
        /**
         * <code>optional .M16.MailDetalInfo reportInfo = 5;</code>
         */
        private com.google.protobuf.SingleFieldBuilder<
            com.znl.proto.M16.MailDetalInfo, com.znl.proto.M16.MailDetalInfo.Builder, com.znl.proto.M16.MailDetalInfoOrBuilder> 
            getReportInfoFieldBuilder() {
          if (reportInfoBuilder_ == null) {
            reportInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                com.znl.proto.M16.MailDetalInfo, com.znl.proto.M16.MailDetalInfo.Builder, com.znl.proto.M16.MailDetalInfoOrBuilder>(
                    reportInfo_,
                    getParentForChildren(),
                    isClean());
            reportInfo_ = null;
          }
          return reportInfoBuilder_;
        }

        // optional .M14.ChatInfo chat = 6;
        private com.znl.proto.M14.ChatInfo chat_ = com.znl.proto.M14.ChatInfo.getDefaultInstance();
        private com.google.protobuf.SingleFieldBuilder<
            com.znl.proto.M14.ChatInfo, com.znl.proto.M14.ChatInfo.Builder, com.znl.proto.M14.ChatInfoOrBuilder> chatBuilder_;
        /**
         * <code>optional .M14.ChatInfo chat = 6;</code>
         */
        public boolean hasChat() {
          return ((bitField0_ & 0x00000020) == 0x00000020);
        }
        /**
         * <code>optional .M14.ChatInfo chat = 6;</code>
         */
        public com.znl.proto.M14.ChatInfo getChat() {
          if (chatBuilder_ == null) {
            return chat_;
          } else {
            return chatBuilder_.getMessage();
          }
        }
        /**
         * <code>optional .M14.ChatInfo chat = 6;</code>
         */
        public Builder setChat(com.znl.proto.M14.ChatInfo value) {
          if (chatBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            chat_ = value;
            onChanged();
          } else {
            chatBuilder_.setMessage(value);
          }
          bitField0_ |= 0x00000020;
          return this;
        }
        /**
         * <code>optional .M14.ChatInfo chat = 6;</code>
         */
        public Builder setChat(
            com.znl.proto.M14.ChatInfo.Builder builderForValue) {
          if (chatBuilder_ == null) {
            chat_ = builderForValue.build();
            onChanged();
          } else {
            chatBuilder_.setMessage(builderForValue.build());
          }
          bitField0_ |= 0x00000020;
          return this;
        }
        /**
         * <code>optional .M14.ChatInfo chat = 6;</code>
         */
        public Builder mergeChat(com.znl.proto.M14.ChatInfo value) {
          if (chatBuilder_ == null) {
            if (((bitField0_ & 0x00000020) == 0x00000020) &&
                chat_ != com.znl.proto.M14.ChatInfo.getDefaultInstance()) {
              chat_ =
                com.znl.proto.M14.ChatInfo.newBuilder(chat_).mergeFrom(value).buildPartial();
            } else {
              chat_ = value;
            }
            onChanged();
          } else {
            chatBuilder_.mergeFrom(value);
          }
          bitField0_ |= 0x00000020;
          return this;
        }
        /**
         * <code>optional .M14.ChatInfo chat = 6;</code>
         */
        public Builder clearChat() {
          if (chatBuilder_ == null) {
            chat_ = com.znl.proto.M14.ChatInfo.getDefaultInstance();
            onChanged();
          } else {
            chatBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000020);
          return this;
        }
        /**
         * <code>optional .M14.ChatInfo chat = 6;</code>
         */
        public com.znl.proto.M14.ChatInfo.Builder getChatBuilder() {
          bitField0_ |= 0x00000020;
          onChanged();
          return getChatFieldBuilder().getBuilder();
        }
        /**
         * <code>optional .M14.ChatInfo chat = 6;</code>
         */
        public com.znl.proto.M14.ChatInfoOrBuilder getChatOrBuilder() {
          if (chatBuilder_ != null) {
            return chatBuilder_.getMessageOrBuilder();
          } else {
            return chat_;
          }
        }
        /**
         * <code>optional .M14.ChatInfo chat = 6;</code>
         */
        private com.google.protobuf.SingleFieldBuilder<
            com.znl.proto.M14.ChatInfo, com.znl.proto.M14.ChatInfo.Builder, com.znl.proto.M14.ChatInfoOrBuilder> 
            getChatFieldBuilder() {
          if (chatBuilder_ == null) {
            chatBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                com.znl.proto.M14.ChatInfo, com.znl.proto.M14.ChatInfo.Builder, com.znl.proto.M14.ChatInfoOrBuilder>(
                    chat_,
                    getParentForChildren(),
                    isClean());
            chat_ = null;
          }
          return chatBuilder_;
        }

        // optional fixed64 id = 7;
        private long id_ ;
        /**
         * <code>optional fixed64 id = 7;</code>
         */
        public boolean hasId() {
          return ((bitField0_ & 0x00000040) == 0x00000040);
        }
        /**
         * <code>optional fixed64 id = 7;</code>
         */
        public long getId() {
          return id_;
        }
        /**
         * <code>optional fixed64 id = 7;</code>
         */
        public Builder setId(long value) {
          bitField0_ |= 0x00000040;
          id_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional fixed64 id = 7;</code>
         */
        public Builder clearId() {
          bitField0_ = (bitField0_ & ~0x00000040);
          id_ = 0L;
          onChanged();
          return this;
        }

        // optional int32 typeId = 8;
        private int typeId_ ;
        /**
         * <code>optional int32 typeId = 8;</code>
         *
         * <pre>
         *佣兵分享的时候传typeId，系统公告时传公告id
         * </pre>
         */
        public boolean hasTypeId() {
          return ((bitField0_ & 0x00000080) == 0x00000080);
        }
        /**
         * <code>optional int32 typeId = 8;</code>
         *
         * <pre>
         *佣兵分享的时候传typeId，系统公告时传公告id
         * </pre>
         */
        public int getTypeId() {
          return typeId_;
        }
        /**
         * <code>optional int32 typeId = 8;</code>
         *
         * <pre>
         *佣兵分享的时候传typeId，系统公告时传公告id
         * </pre>
         */
        public Builder setTypeId(int value) {
          bitField0_ |= 0x00000080;
          typeId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 typeId = 8;</code>
         *
         * <pre>
         *佣兵分享的时候传typeId，系统公告时传公告id
         * </pre>
         */
        public Builder clearTypeId() {
          bitField0_ = (bitField0_ & ~0x00000080);
          typeId_ = 0;
          onChanged();
          return this;
        }

        // optional int32 shareType = 9;
        private int shareType_ ;
        /**
         * <code>optional int32 shareType = 9;</code>
         *
         * <pre>
         *1:世界分享，2：军团分享
         * </pre>
         */
        public boolean hasShareType() {
          return ((bitField0_ & 0x00000100) == 0x00000100);
        }
        /**
         * <code>optional int32 shareType = 9;</code>
         *
         * <pre>
         *1:世界分享，2：军团分享
         * </pre>
         */
        public int getShareType() {
          return shareType_;
        }
        /**
         * <code>optional int32 shareType = 9;</code>
         *
         * <pre>
         *1:世界分享，2：军团分享
         * </pre>
         */
        public Builder setShareType(int value) {
          bitField0_ |= 0x00000100;
          shareType_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 shareType = 9;</code>
         *
         * <pre>
         *1:世界分享，2：军团分享
         * </pre>
         */
        public Builder clearShareType() {
          bitField0_ = (bitField0_ & ~0x00000100);
          shareType_ = 0;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:M25.M250000.S2C)
      }

      static {
        defaultInstance = new S2C(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:M25.M250000.S2C)
    }

    public interface C2SOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required int32 type = 1;
      /**
       * <code>required int32 type = 1;</code>
       *
       * <pre>
       *1：佣兵分享，2：竞技场战报分享，3：野外战报分享，4：系统公告
       * </pre>
       */
      boolean hasType();
      /**
       * <code>required int32 type = 1;</code>
       *
       * <pre>
       *1：佣兵分享，2：竞技场战报分享，3：野外战报分享，4：系统公告
       * </pre>
       */
      int getType();

      // optional fixed64 id = 2;
      /**
       * <code>optional fixed64 id = 2;</code>
       */
      boolean hasId();
      /**
       * <code>optional fixed64 id = 2;</code>
       */
      long getId();

      // optional int32 typeId = 3;
      /**
       * <code>optional int32 typeId = 3;</code>
       *
       * <pre>
       *佣兵分享的时候传typeId
       * </pre>
       */
      boolean hasTypeId();
      /**
       * <code>optional int32 typeId = 3;</code>
       *
       * <pre>
       *佣兵分享的时候传typeId
       * </pre>
       */
      int getTypeId();

      // required int32 shareType = 4;
      /**
       * <code>required int32 shareType = 4;</code>
       *
       * <pre>
       *1:世界分享，2：军团分享
       * </pre>
       */
      boolean hasShareType();
      /**
       * <code>required int32 shareType = 4;</code>
       *
       * <pre>
       *1:世界分享，2：军团分享
       * </pre>
       */
      int getShareType();
    }
    /**
     * Protobuf type {@code M25.M250000.C2S}
     */
    public static final class C2S extends
        com.google.protobuf.GeneratedMessage
        implements C2SOrBuilder {
      // Use C2S.newBuilder() to construct.
      private C2S(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private C2S(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final C2S defaultInstance;
      public static C2S getDefaultInstance() {
        return defaultInstance;
      }

      public C2S getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private C2S(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                type_ = input.readInt32();
                break;
              }
              case 17: {
                bitField0_ |= 0x00000002;
                id_ = input.readFixed64();
                break;
              }
              case 24: {
                bitField0_ |= 0x00000004;
                typeId_ = input.readInt32();
                break;
              }
              case 32: {
                bitField0_ |= 0x00000008;
                shareType_ = input.readInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.znl.proto.M25.internal_static_M25_M250000_C2S_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.znl.proto.M25.internal_static_M25_M250000_C2S_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.znl.proto.M25.M250000.C2S.class, com.znl.proto.M25.M250000.C2S.Builder.class);
      }

      public static com.google.protobuf.Parser<C2S> PARSER =
          new com.google.protobuf.AbstractParser<C2S>() {
        public C2S parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new C2S(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<C2S> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required int32 type = 1;
      public static final int TYPE_FIELD_NUMBER = 1;
      private int type_;
      /**
       * <code>required int32 type = 1;</code>
       *
       * <pre>
       *1：佣兵分享，2：竞技场战报分享，3：野外战报分享，4：系统公告
       * </pre>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 type = 1;</code>
       *
       * <pre>
       *1：佣兵分享，2：竞技场战报分享，3：野外战报分享，4：系统公告
       * </pre>
       */
      public int getType() {
        return type_;
      }

      // optional fixed64 id = 2;
      public static final int ID_FIELD_NUMBER = 2;
      private long id_;
      /**
       * <code>optional fixed64 id = 2;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional fixed64 id = 2;</code>
       */
      public long getId() {
        return id_;
      }

      // optional int32 typeId = 3;
      public static final int TYPEID_FIELD_NUMBER = 3;
      private int typeId_;
      /**
       * <code>optional int32 typeId = 3;</code>
       *
       * <pre>
       *佣兵分享的时候传typeId
       * </pre>
       */
      public boolean hasTypeId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 typeId = 3;</code>
       *
       * <pre>
       *佣兵分享的时候传typeId
       * </pre>
       */
      public int getTypeId() {
        return typeId_;
      }

      // required int32 shareType = 4;
      public static final int SHARETYPE_FIELD_NUMBER = 4;
      private int shareType_;
      /**
       * <code>required int32 shareType = 4;</code>
       *
       * <pre>
       *1:世界分享，2：军团分享
       * </pre>
       */
      public boolean hasShareType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 shareType = 4;</code>
       *
       * <pre>
       *1:世界分享，2：军团分享
       * </pre>
       */
      public int getShareType() {
        return shareType_;
      }

      private void initFields() {
        type_ = 0;
        id_ = 0L;
        typeId_ = 0;
        shareType_ = 0;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasType()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasShareType()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, type_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeFixed64(2, id_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeInt32(3, typeId_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeInt32(4, shareType_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, type_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeFixed64Size(2, id_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(3, typeId_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(4, shareType_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.znl.proto.M25.M250000.C2S parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.znl.proto.M25.M250000.C2S parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.znl.proto.M25.M250000.C2S parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.znl.proto.M25.M250000.C2S parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.znl.proto.M25.M250000.C2S parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.znl.proto.M25.M250000.C2S parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.znl.proto.M25.M250000.C2S parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.znl.proto.M25.M250000.C2S parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.znl.proto.M25.M250000.C2S parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.znl.proto.M25.M250000.C2S parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.znl.proto.M25.M250000.C2S prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code M25.M250000.C2S}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.znl.proto.M25.M250000.C2SOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.znl.proto.M25.internal_static_M25_M250000_C2S_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.znl.proto.M25.internal_static_M25_M250000_C2S_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.znl.proto.M25.M250000.C2S.class, com.znl.proto.M25.M250000.C2S.Builder.class);
        }

        // Construct using com.znl.proto.M25.M250000.C2S.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          type_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          id_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000002);
          typeId_ = 0;
          bitField0_ = (bitField0_ & ~0x00000004);
          shareType_ = 0;
          bitField0_ = (bitField0_ & ~0x00000008);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.znl.proto.M25.internal_static_M25_M250000_C2S_descriptor;
        }

        public com.znl.proto.M25.M250000.C2S getDefaultInstanceForType() {
          return com.znl.proto.M25.M250000.C2S.getDefaultInstance();
        }

        public com.znl.proto.M25.M250000.C2S build() {
          com.znl.proto.M25.M250000.C2S result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.znl.proto.M25.M250000.C2S buildPartial() {
          com.znl.proto.M25.M250000.C2S result = new com.znl.proto.M25.M250000.C2S(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.type_ = type_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.id_ = id_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.typeId_ = typeId_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.shareType_ = shareType_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.znl.proto.M25.M250000.C2S) {
            return mergeFrom((com.znl.proto.M25.M250000.C2S)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.znl.proto.M25.M250000.C2S other) {
          if (other == com.znl.proto.M25.M250000.C2S.getDefaultInstance()) return this;
          if (other.hasType()) {
            setType(other.getType());
          }
          if (other.hasId()) {
            setId(other.getId());
          }
          if (other.hasTypeId()) {
            setTypeId(other.getTypeId());
          }
          if (other.hasShareType()) {
            setShareType(other.getShareType());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasType()) {
            
            return false;
          }
          if (!hasShareType()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.znl.proto.M25.M250000.C2S parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.znl.proto.M25.M250000.C2S) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required int32 type = 1;
        private int type_ ;
        /**
         * <code>required int32 type = 1;</code>
         *
         * <pre>
         *1：佣兵分享，2：竞技场战报分享，3：野外战报分享，4：系统公告
         * </pre>
         */
        public boolean hasType() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required int32 type = 1;</code>
         *
         * <pre>
         *1：佣兵分享，2：竞技场战报分享，3：野外战报分享，4：系统公告
         * </pre>
         */
        public int getType() {
          return type_;
        }
        /**
         * <code>required int32 type = 1;</code>
         *
         * <pre>
         *1：佣兵分享，2：竞技场战报分享，3：野外战报分享，4：系统公告
         * </pre>
         */
        public Builder setType(int value) {
          bitField0_ |= 0x00000001;
          type_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 type = 1;</code>
         *
         * <pre>
         *1：佣兵分享，2：竞技场战报分享，3：野外战报分享，4：系统公告
         * </pre>
         */
        public Builder clearType() {
          bitField0_ = (bitField0_ & ~0x00000001);
          type_ = 0;
          onChanged();
          return this;
        }

        // optional fixed64 id = 2;
        private long id_ ;
        /**
         * <code>optional fixed64 id = 2;</code>
         */
        public boolean hasId() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional fixed64 id = 2;</code>
         */
        public long getId() {
          return id_;
        }
        /**
         * <code>optional fixed64 id = 2;</code>
         */
        public Builder setId(long value) {
          bitField0_ |= 0x00000002;
          id_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional fixed64 id = 2;</code>
         */
        public Builder clearId() {
          bitField0_ = (bitField0_ & ~0x00000002);
          id_ = 0L;
          onChanged();
          return this;
        }

        // optional int32 typeId = 3;
        private int typeId_ ;
        /**
         * <code>optional int32 typeId = 3;</code>
         *
         * <pre>
         *佣兵分享的时候传typeId
         * </pre>
         */
        public boolean hasTypeId() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional int32 typeId = 3;</code>
         *
         * <pre>
         *佣兵分享的时候传typeId
         * </pre>
         */
        public int getTypeId() {
          return typeId_;
        }
        /**
         * <code>optional int32 typeId = 3;</code>
         *
         * <pre>
         *佣兵分享的时候传typeId
         * </pre>
         */
        public Builder setTypeId(int value) {
          bitField0_ |= 0x00000004;
          typeId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 typeId = 3;</code>
         *
         * <pre>
         *佣兵分享的时候传typeId
         * </pre>
         */
        public Builder clearTypeId() {
          bitField0_ = (bitField0_ & ~0x00000004);
          typeId_ = 0;
          onChanged();
          return this;
        }

        // required int32 shareType = 4;
        private int shareType_ ;
        /**
         * <code>required int32 shareType = 4;</code>
         *
         * <pre>
         *1:世界分享，2：军团分享
         * </pre>
         */
        public boolean hasShareType() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>required int32 shareType = 4;</code>
         *
         * <pre>
         *1:世界分享，2：军团分享
         * </pre>
         */
        public int getShareType() {
          return shareType_;
        }
        /**
         * <code>required int32 shareType = 4;</code>
         *
         * <pre>
         *1:世界分享，2：军团分享
         * </pre>
         */
        public Builder setShareType(int value) {
          bitField0_ |= 0x00000008;
          shareType_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 shareType = 4;</code>
         *
         * <pre>
         *1:世界分享，2：军团分享
         * </pre>
         */
        public Builder clearShareType() {
          bitField0_ = (bitField0_ & ~0x00000008);
          shareType_ = 0;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:M25.M250000.C2S)
      }

      static {
        defaultInstance = new C2S(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:M25.M250000.C2S)
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.znl.proto.M25.M250000 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.znl.proto.M25.M250000 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.znl.proto.M25.M250000 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.znl.proto.M25.M250000 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.znl.proto.M25.M250000 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.znl.proto.M25.M250000 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.znl.proto.M25.M250000 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.znl.proto.M25.M250000 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.znl.proto.M25.M250000 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.znl.proto.M25.M250000 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.znl.proto.M25.M250000 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code M25.M250000}
     *
     * <pre>
     *分享功能
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.znl.proto.M25.M250000OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.znl.proto.M25.internal_static_M25_M250000_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.znl.proto.M25.internal_static_M25_M250000_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.znl.proto.M25.M250000.class, com.znl.proto.M25.M250000.Builder.class);
      }

      // Construct using com.znl.proto.M25.M250000.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.znl.proto.M25.internal_static_M25_M250000_descriptor;
      }

      public com.znl.proto.M25.M250000 getDefaultInstanceForType() {
        return com.znl.proto.M25.M250000.getDefaultInstance();
      }

      public com.znl.proto.M25.M250000 build() {
        com.znl.proto.M25.M250000 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.znl.proto.M25.M250000 buildPartial() {
        com.znl.proto.M25.M250000 result = new com.znl.proto.M25.M250000(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.znl.proto.M25.M250000) {
          return mergeFrom((com.znl.proto.M25.M250000)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.znl.proto.M25.M250000 other) {
        if (other == com.znl.proto.M25.M250000.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.znl.proto.M25.M250000 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.znl.proto.M25.M250000) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:M25.M250000)
    }

    static {
      defaultInstance = new M250000(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:M25.M250000)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_M25_M250000_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_M25_M250000_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_M25_M250000_S2C_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_M25_M250000_S2C_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_M25_M250000_C2S_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_M25_M250000_C2S_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tM25.proto\022\003M25\032\014Common.proto\032\tM20.prot" +
      "o\032\tM16.proto\032\tM14.proto\"\265\002\n\007M250000\032\345\001\n\003" +
      "S2C\022\n\n\002rs\030\001 \002(\005\022\014\n\004type\030\002 \001(\005\022(\n\013soldier" +
      "Info\030\003 \001(\0132\023.Common.SoldierInfo\022&\n\tarean" +
      "Info\030\004 \001(\0132\023.M20.PerDetailInfos\022&\n\nrepor" +
      "tInfo\030\005 \001(\0132\022.M16.MailDetalInfo\022\033\n\004chat\030" +
      "\006 \001(\0132\r.M14.ChatInfo\022\n\n\002id\030\007 \001(\006\022\016\n\006type" +
      "Id\030\010 \001(\005\022\021\n\tshareType\030\t \001(\005\032B\n\003C2S\022\014\n\004ty" +
      "pe\030\001 \002(\005\022\n\n\002id\030\002 \001(\006\022\016\n\006typeId\030\003 \001(\005\022\021\n\t" +
      "shareType\030\004 \002(\005B\024\n\rcom.znl.protoB\003M25"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_M25_M250000_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_M25_M250000_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_M25_M250000_descriptor,
              new java.lang.String[] { });
          internal_static_M25_M250000_S2C_descriptor =
            internal_static_M25_M250000_descriptor.getNestedTypes().get(0);
          internal_static_M25_M250000_S2C_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_M25_M250000_S2C_descriptor,
              new java.lang.String[] { "Rs", "Type", "SoldierInfo", "AreanInfo", "ReportInfo", "Chat", "Id", "TypeId", "ShareType", });
          internal_static_M25_M250000_C2S_descriptor =
            internal_static_M25_M250000_descriptor.getNestedTypes().get(1);
          internal_static_M25_M250000_C2S_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_M25_M250000_C2S_descriptor,
              new java.lang.String[] { "Type", "Id", "TypeId", "ShareType", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.znl.proto.Common.getDescriptor(),
          com.znl.proto.M20.getDescriptor(),
          com.znl.proto.M16.getDescriptor(),
          com.znl.proto.M14.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
