// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Commoms.proto

package com.tworr.msg.protocal;

public final class Commons {
  private Commons() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ResponseInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 status = 1;
    /**
     * <code>required int32 status = 1;</code>
     *
     * <pre>
     *状态
     * </pre>
     */
    boolean hasStatus();
    /**
     * <code>required int32 status = 1;</code>
     *
     * <pre>
     *状态
     * </pre>
     */
    int getStatus();

    // optional string msg = 2;
    /**
     * <code>optional string msg = 2;</code>
     *
     * <pre>
     *提示消息
     * </pre>
     */
    boolean hasMsg();
    /**
     * <code>optional string msg = 2;</code>
     *
     * <pre>
     *提示消息
     * </pre>
     */
    java.lang.String getMsg();
    /**
     * <code>optional string msg = 2;</code>
     *
     * <pre>
     *提示消息
     * </pre>
     */
    com.google.protobuf.ByteString
        getMsgBytes();
  }
  /**
   * Protobuf type {@code com.tworr.msg.Commons.ResponseInfo}
   *
   * <pre>
   *返回客户端的实体
   * </pre>
   */
  public static final class ResponseInfo extends
      com.google.protobuf.GeneratedMessage
      implements ResponseInfoOrBuilder {
    // Use ResponseInfo.newBuilder() to construct.
    private ResponseInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ResponseInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ResponseInfo defaultInstance;
    public static ResponseInfo getDefaultInstance() {
      return defaultInstance;
    }

    public ResponseInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ResponseInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              status_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              msg_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tworr.msg.protocal.Commons.internal_static_com_tworr_msg_Commons_ResponseInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tworr.msg.protocal.Commons.internal_static_com_tworr_msg_Commons_ResponseInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tworr.msg.protocal.Commons.ResponseInfo.class, com.tworr.msg.protocal.Commons.ResponseInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<ResponseInfo> PARSER =
        new com.google.protobuf.AbstractParser<ResponseInfo>() {
      public ResponseInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResponseInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ResponseInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 status = 1;
    public static final int STATUS_FIELD_NUMBER = 1;
    private int status_;
    /**
     * <code>required int32 status = 1;</code>
     *
     * <pre>
     *状态
     * </pre>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 status = 1;</code>
     *
     * <pre>
     *状态
     * </pre>
     */
    public int getStatus() {
      return status_;
    }

    // optional string msg = 2;
    public static final int MSG_FIELD_NUMBER = 2;
    private java.lang.Object msg_;
    /**
     * <code>optional string msg = 2;</code>
     *
     * <pre>
     *提示消息
     * </pre>
     */
    public boolean hasMsg() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string msg = 2;</code>
     *
     * <pre>
     *提示消息
     * </pre>
     */
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string msg = 2;</code>
     *
     * <pre>
     *提示消息
     * </pre>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      status_ = 0;
      msg_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, status_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMsgBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, status_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMsgBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.tworr.msg.protocal.Commons.ResponseInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tworr.msg.protocal.Commons.ResponseInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tworr.msg.protocal.Commons.ResponseInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tworr.msg.protocal.Commons.ResponseInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tworr.msg.protocal.Commons.ResponseInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.tworr.msg.protocal.Commons.ResponseInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.tworr.msg.protocal.Commons.ResponseInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.tworr.msg.protocal.Commons.ResponseInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.tworr.msg.protocal.Commons.ResponseInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.tworr.msg.protocal.Commons.ResponseInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.tworr.msg.protocal.Commons.ResponseInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.tworr.msg.Commons.ResponseInfo}
     *
     * <pre>
     *返回客户端的实体
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.tworr.msg.protocal.Commons.ResponseInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tworr.msg.protocal.Commons.internal_static_com_tworr_msg_Commons_ResponseInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tworr.msg.protocal.Commons.internal_static_com_tworr_msg_Commons_ResponseInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tworr.msg.protocal.Commons.ResponseInfo.class, com.tworr.msg.protocal.Commons.ResponseInfo.Builder.class);
      }

      // Construct using com.tworr.msg.protocal.Commons.ResponseInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        status_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        msg_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tworr.msg.protocal.Commons.internal_static_com_tworr_msg_Commons_ResponseInfo_descriptor;
      }

      public com.tworr.msg.protocal.Commons.ResponseInfo getDefaultInstanceForType() {
        return com.tworr.msg.protocal.Commons.ResponseInfo.getDefaultInstance();
      }

      public com.tworr.msg.protocal.Commons.ResponseInfo build() {
        com.tworr.msg.protocal.Commons.ResponseInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.tworr.msg.protocal.Commons.ResponseInfo buildPartial() {
        com.tworr.msg.protocal.Commons.ResponseInfo result = new com.tworr.msg.protocal.Commons.ResponseInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.status_ = status_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.msg_ = msg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tworr.msg.protocal.Commons.ResponseInfo) {
          return mergeFrom((com.tworr.msg.protocal.Commons.ResponseInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tworr.msg.protocal.Commons.ResponseInfo other) {
        if (other == com.tworr.msg.protocal.Commons.ResponseInfo.getDefaultInstance()) return this;
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasMsg()) {
          bitField0_ |= 0x00000002;
          msg_ = other.msg_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasStatus()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tworr.msg.protocal.Commons.ResponseInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tworr.msg.protocal.Commons.ResponseInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 status = 1;
      private int status_ ;
      /**
       * <code>required int32 status = 1;</code>
       *
       * <pre>
       *状态
       * </pre>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 status = 1;</code>
       *
       * <pre>
       *状态
       * </pre>
       */
      public int getStatus() {
        return status_;
      }
      /**
       * <code>required int32 status = 1;</code>
       *
       * <pre>
       *状态
       * </pre>
       */
      public Builder setStatus(int value) {
        bitField0_ |= 0x00000001;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 status = 1;</code>
       *
       * <pre>
       *状态
       * </pre>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = 0;
        onChanged();
        return this;
      }

      // optional string msg = 2;
      private java.lang.Object msg_ = "";
      /**
       * <code>optional string msg = 2;</code>
       *
       * <pre>
       *提示消息
       * </pre>
       */
      public boolean hasMsg() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string msg = 2;</code>
       *
       * <pre>
       *提示消息
       * </pre>
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string msg = 2;</code>
       *
       * <pre>
       *提示消息
       * </pre>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string msg = 2;</code>
       *
       * <pre>
       *提示消息
       * </pre>
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg = 2;</code>
       *
       * <pre>
       *提示消息
       * </pre>
       */
      public Builder clearMsg() {
        bitField0_ = (bitField0_ & ~0x00000002);
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg = 2;</code>
       *
       * <pre>
       *提示消息
       * </pre>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        msg_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.tworr.msg.Commons.ResponseInfo)
    }

    static {
      defaultInstance = new ResponseInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.tworr.msg.Commons.ResponseInfo)
  }

  public interface SimpleUserInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string id = 1;
    /**
     * <code>required string id = 1;</code>
     *
     * <pre>
     *用户id
     * </pre>
     */
    boolean hasId();
    /**
     * <code>required string id = 1;</code>
     *
     * <pre>
     *用户id
     * </pre>
     */
    java.lang.String getId();
    /**
     * <code>required string id = 1;</code>
     *
     * <pre>
     *用户id
     * </pre>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    // required string nickName = 2;
    /**
     * <code>required string nickName = 2;</code>
     *
     * <pre>
     *用户昵称
     * </pre>
     */
    boolean hasNickName();
    /**
     * <code>required string nickName = 2;</code>
     *
     * <pre>
     *用户昵称
     * </pre>
     */
    java.lang.String getNickName();
    /**
     * <code>required string nickName = 2;</code>
     *
     * <pre>
     *用户昵称
     * </pre>
     */
    com.google.protobuf.ByteString
        getNickNameBytes();

    // required string headerPath = 3;
    /**
     * <code>required string headerPath = 3;</code>
     *
     * <pre>
     *头像地址
     * </pre>
     */
    boolean hasHeaderPath();
    /**
     * <code>required string headerPath = 3;</code>
     *
     * <pre>
     *头像地址
     * </pre>
     */
    java.lang.String getHeaderPath();
    /**
     * <code>required string headerPath = 3;</code>
     *
     * <pre>
     *头像地址
     * </pre>
     */
    com.google.protobuf.ByteString
        getHeaderPathBytes();

    // required string email = 4;
    /**
     * <code>required string email = 4;</code>
     *
     * <pre>
     *邮箱
     * </pre>
     */
    boolean hasEmail();
    /**
     * <code>required string email = 4;</code>
     *
     * <pre>
     *邮箱
     * </pre>
     */
    java.lang.String getEmail();
    /**
     * <code>required string email = 4;</code>
     *
     * <pre>
     *邮箱
     * </pre>
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    // optional int32 level = 5;
    /**
     * <code>optional int32 level = 5;</code>
     *
     * <pre>
     *等级
     * </pre>
     */
    boolean hasLevel();
    /**
     * <code>optional int32 level = 5;</code>
     *
     * <pre>
     *等级
     * </pre>
     */
    int getLevel();

    // required bool isOnline = 6;
    /**
     * <code>required bool isOnline = 6;</code>
     *
     * <pre>
     *是否在线
     * </pre>
     */
    boolean hasIsOnline();
    /**
     * <code>required bool isOnline = 6;</code>
     *
     * <pre>
     *是否在线
     * </pre>
     */
    boolean getIsOnline();
  }
  /**
   * Protobuf type {@code com.tworr.msg.Commons.SimpleUserInfo}
   */
  public static final class SimpleUserInfo extends
      com.google.protobuf.GeneratedMessage
      implements SimpleUserInfoOrBuilder {
    // Use SimpleUserInfo.newBuilder() to construct.
    private SimpleUserInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SimpleUserInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SimpleUserInfo defaultInstance;
    public static SimpleUserInfo getDefaultInstance() {
      return defaultInstance;
    }

    public SimpleUserInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SimpleUserInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              nickName_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              headerPath_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              email_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              level_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              isOnline_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tworr.msg.protocal.Commons.internal_static_com_tworr_msg_Commons_SimpleUserInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tworr.msg.protocal.Commons.internal_static_com_tworr_msg_Commons_SimpleUserInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tworr.msg.protocal.Commons.SimpleUserInfo.class, com.tworr.msg.protocal.Commons.SimpleUserInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<SimpleUserInfo> PARSER =
        new com.google.protobuf.AbstractParser<SimpleUserInfo>() {
      public SimpleUserInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SimpleUserInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SimpleUserInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    /**
     * <code>required string id = 1;</code>
     *
     * <pre>
     *用户id
     * </pre>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string id = 1;</code>
     *
     * <pre>
     *用户id
     * </pre>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string id = 1;</code>
     *
     * <pre>
     *用户id
     * </pre>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string nickName = 2;
    public static final int NICKNAME_FIELD_NUMBER = 2;
    private java.lang.Object nickName_;
    /**
     * <code>required string nickName = 2;</code>
     *
     * <pre>
     *用户昵称
     * </pre>
     */
    public boolean hasNickName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string nickName = 2;</code>
     *
     * <pre>
     *用户昵称
     * </pre>
     */
    public java.lang.String getNickName() {
      java.lang.Object ref = nickName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          nickName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string nickName = 2;</code>
     *
     * <pre>
     *用户昵称
     * </pre>
     */
    public com.google.protobuf.ByteString
        getNickNameBytes() {
      java.lang.Object ref = nickName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nickName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string headerPath = 3;
    public static final int HEADERPATH_FIELD_NUMBER = 3;
    private java.lang.Object headerPath_;
    /**
     * <code>required string headerPath = 3;</code>
     *
     * <pre>
     *头像地址
     * </pre>
     */
    public boolean hasHeaderPath() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string headerPath = 3;</code>
     *
     * <pre>
     *头像地址
     * </pre>
     */
    public java.lang.String getHeaderPath() {
      java.lang.Object ref = headerPath_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          headerPath_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string headerPath = 3;</code>
     *
     * <pre>
     *头像地址
     * </pre>
     */
    public com.google.protobuf.ByteString
        getHeaderPathBytes() {
      java.lang.Object ref = headerPath_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        headerPath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string email = 4;
    public static final int EMAIL_FIELD_NUMBER = 4;
    private java.lang.Object email_;
    /**
     * <code>required string email = 4;</code>
     *
     * <pre>
     *邮箱
     * </pre>
     */
    public boolean hasEmail() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string email = 4;</code>
     *
     * <pre>
     *邮箱
     * </pre>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          email_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string email = 4;</code>
     *
     * <pre>
     *邮箱
     * </pre>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 level = 5;
    public static final int LEVEL_FIELD_NUMBER = 5;
    private int level_;
    /**
     * <code>optional int32 level = 5;</code>
     *
     * <pre>
     *等级
     * </pre>
     */
    public boolean hasLevel() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 level = 5;</code>
     *
     * <pre>
     *等级
     * </pre>
     */
    public int getLevel() {
      return level_;
    }

    // required bool isOnline = 6;
    public static final int ISONLINE_FIELD_NUMBER = 6;
    private boolean isOnline_;
    /**
     * <code>required bool isOnline = 6;</code>
     *
     * <pre>
     *是否在线
     * </pre>
     */
    public boolean hasIsOnline() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required bool isOnline = 6;</code>
     *
     * <pre>
     *是否在线
     * </pre>
     */
    public boolean getIsOnline() {
      return isOnline_;
    }

    private void initFields() {
      id_ = "";
      nickName_ = "";
      headerPath_ = "";
      email_ = "";
      level_ = 0;
      isOnline_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNickName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHeaderPath()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEmail()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIsOnline()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNickNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getHeaderPathBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getEmailBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, level_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBool(6, isOnline_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNickNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getHeaderPathBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getEmailBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, level_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, isOnline_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.tworr.msg.protocal.Commons.SimpleUserInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tworr.msg.protocal.Commons.SimpleUserInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tworr.msg.protocal.Commons.SimpleUserInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tworr.msg.protocal.Commons.SimpleUserInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tworr.msg.protocal.Commons.SimpleUserInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.tworr.msg.protocal.Commons.SimpleUserInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.tworr.msg.protocal.Commons.SimpleUserInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.tworr.msg.protocal.Commons.SimpleUserInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.tworr.msg.protocal.Commons.SimpleUserInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.tworr.msg.protocal.Commons.SimpleUserInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.tworr.msg.protocal.Commons.SimpleUserInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.tworr.msg.Commons.SimpleUserInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.tworr.msg.protocal.Commons.SimpleUserInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tworr.msg.protocal.Commons.internal_static_com_tworr_msg_Commons_SimpleUserInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tworr.msg.protocal.Commons.internal_static_com_tworr_msg_Commons_SimpleUserInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tworr.msg.protocal.Commons.SimpleUserInfo.class, com.tworr.msg.protocal.Commons.SimpleUserInfo.Builder.class);
      }

      // Construct using com.tworr.msg.protocal.Commons.SimpleUserInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        nickName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        headerPath_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        email_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        level_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        isOnline_ = false;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tworr.msg.protocal.Commons.internal_static_com_tworr_msg_Commons_SimpleUserInfo_descriptor;
      }

      public com.tworr.msg.protocal.Commons.SimpleUserInfo getDefaultInstanceForType() {
        return com.tworr.msg.protocal.Commons.SimpleUserInfo.getDefaultInstance();
      }

      public com.tworr.msg.protocal.Commons.SimpleUserInfo build() {
        com.tworr.msg.protocal.Commons.SimpleUserInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.tworr.msg.protocal.Commons.SimpleUserInfo buildPartial() {
        com.tworr.msg.protocal.Commons.SimpleUserInfo result = new com.tworr.msg.protocal.Commons.SimpleUserInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.nickName_ = nickName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.headerPath_ = headerPath_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.email_ = email_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.level_ = level_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.isOnline_ = isOnline_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tworr.msg.protocal.Commons.SimpleUserInfo) {
          return mergeFrom((com.tworr.msg.protocal.Commons.SimpleUserInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tworr.msg.protocal.Commons.SimpleUserInfo other) {
        if (other == com.tworr.msg.protocal.Commons.SimpleUserInfo.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasNickName()) {
          bitField0_ |= 0x00000002;
          nickName_ = other.nickName_;
          onChanged();
        }
        if (other.hasHeaderPath()) {
          bitField0_ |= 0x00000004;
          headerPath_ = other.headerPath_;
          onChanged();
        }
        if (other.hasEmail()) {
          bitField0_ |= 0x00000008;
          email_ = other.email_;
          onChanged();
        }
        if (other.hasLevel()) {
          setLevel(other.getLevel());
        }
        if (other.hasIsOnline()) {
          setIsOnline(other.getIsOnline());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasNickName()) {
          
          return false;
        }
        if (!hasHeaderPath()) {
          
          return false;
        }
        if (!hasEmail()) {
          
          return false;
        }
        if (!hasIsOnline()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tworr.msg.protocal.Commons.SimpleUserInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tworr.msg.protocal.Commons.SimpleUserInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string id = 1;
      private java.lang.Object id_ = "";
      /**
       * <code>required string id = 1;</code>
       *
       * <pre>
       *用户id
       * </pre>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string id = 1;</code>
       *
       * <pre>
       *用户id
       * </pre>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       *
       * <pre>
       *用户id
       * </pre>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       *
       * <pre>
       *用户id
       * </pre>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       *
       * <pre>
       *用户id
       * </pre>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       *
       * <pre>
       *用户id
       * </pre>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      // required string nickName = 2;
      private java.lang.Object nickName_ = "";
      /**
       * <code>required string nickName = 2;</code>
       *
       * <pre>
       *用户昵称
       * </pre>
       */
      public boolean hasNickName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string nickName = 2;</code>
       *
       * <pre>
       *用户昵称
       * </pre>
       */
      public java.lang.String getNickName() {
        java.lang.Object ref = nickName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          nickName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string nickName = 2;</code>
       *
       * <pre>
       *用户昵称
       * </pre>
       */
      public com.google.protobuf.ByteString
          getNickNameBytes() {
        java.lang.Object ref = nickName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nickName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string nickName = 2;</code>
       *
       * <pre>
       *用户昵称
       * </pre>
       */
      public Builder setNickName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        nickName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string nickName = 2;</code>
       *
       * <pre>
       *用户昵称
       * </pre>
       */
      public Builder clearNickName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        nickName_ = getDefaultInstance().getNickName();
        onChanged();
        return this;
      }
      /**
       * <code>required string nickName = 2;</code>
       *
       * <pre>
       *用户昵称
       * </pre>
       */
      public Builder setNickNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        nickName_ = value;
        onChanged();
        return this;
      }

      // required string headerPath = 3;
      private java.lang.Object headerPath_ = "";
      /**
       * <code>required string headerPath = 3;</code>
       *
       * <pre>
       *头像地址
       * </pre>
       */
      public boolean hasHeaderPath() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string headerPath = 3;</code>
       *
       * <pre>
       *头像地址
       * </pre>
       */
      public java.lang.String getHeaderPath() {
        java.lang.Object ref = headerPath_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          headerPath_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string headerPath = 3;</code>
       *
       * <pre>
       *头像地址
       * </pre>
       */
      public com.google.protobuf.ByteString
          getHeaderPathBytes() {
        java.lang.Object ref = headerPath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          headerPath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string headerPath = 3;</code>
       *
       * <pre>
       *头像地址
       * </pre>
       */
      public Builder setHeaderPath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        headerPath_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string headerPath = 3;</code>
       *
       * <pre>
       *头像地址
       * </pre>
       */
      public Builder clearHeaderPath() {
        bitField0_ = (bitField0_ & ~0x00000004);
        headerPath_ = getDefaultInstance().getHeaderPath();
        onChanged();
        return this;
      }
      /**
       * <code>required string headerPath = 3;</code>
       *
       * <pre>
       *头像地址
       * </pre>
       */
      public Builder setHeaderPathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        headerPath_ = value;
        onChanged();
        return this;
      }

      // required string email = 4;
      private java.lang.Object email_ = "";
      /**
       * <code>required string email = 4;</code>
       *
       * <pre>
       *邮箱
       * </pre>
       */
      public boolean hasEmail() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string email = 4;</code>
       *
       * <pre>
       *邮箱
       * </pre>
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string email = 4;</code>
       *
       * <pre>
       *邮箱
       * </pre>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string email = 4;</code>
       *
       * <pre>
       *邮箱
       * </pre>
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string email = 4;</code>
       *
       * <pre>
       *邮箱
       * </pre>
       */
      public Builder clearEmail() {
        bitField0_ = (bitField0_ & ~0x00000008);
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>required string email = 4;</code>
       *
       * <pre>
       *邮箱
       * </pre>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        email_ = value;
        onChanged();
        return this;
      }

      // optional int32 level = 5;
      private int level_ ;
      /**
       * <code>optional int32 level = 5;</code>
       *
       * <pre>
       *等级
       * </pre>
       */
      public boolean hasLevel() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 level = 5;</code>
       *
       * <pre>
       *等级
       * </pre>
       */
      public int getLevel() {
        return level_;
      }
      /**
       * <code>optional int32 level = 5;</code>
       *
       * <pre>
       *等级
       * </pre>
       */
      public Builder setLevel(int value) {
        bitField0_ |= 0x00000010;
        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 level = 5;</code>
       *
       * <pre>
       *等级
       * </pre>
       */
      public Builder clearLevel() {
        bitField0_ = (bitField0_ & ~0x00000010);
        level_ = 0;
        onChanged();
        return this;
      }

      // required bool isOnline = 6;
      private boolean isOnline_ ;
      /**
       * <code>required bool isOnline = 6;</code>
       *
       * <pre>
       *是否在线
       * </pre>
       */
      public boolean hasIsOnline() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required bool isOnline = 6;</code>
       *
       * <pre>
       *是否在线
       * </pre>
       */
      public boolean getIsOnline() {
        return isOnline_;
      }
      /**
       * <code>required bool isOnline = 6;</code>
       *
       * <pre>
       *是否在线
       * </pre>
       */
      public Builder setIsOnline(boolean value) {
        bitField0_ |= 0x00000020;
        isOnline_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool isOnline = 6;</code>
       *
       * <pre>
       *是否在线
       * </pre>
       */
      public Builder clearIsOnline() {
        bitField0_ = (bitField0_ & ~0x00000020);
        isOnline_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.tworr.msg.Commons.SimpleUserInfo)
    }

    static {
      defaultInstance = new SimpleUserInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.tworr.msg.Commons.SimpleUserInfo)
  }

  public interface ImageMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required bytes file = 1;
    /**
     * <code>required bytes file = 1;</code>
     *
     * <pre>
     *图片内容
     * </pre>
     */
    boolean hasFile();
    /**
     * <code>required bytes file = 1;</code>
     *
     * <pre>
     *图片内容
     * </pre>
     */
    com.google.protobuf.ByteString getFile();

    // optional string fileName = 2;
    /**
     * <code>optional string fileName = 2;</code>
     *
     * <pre>
     *图片名称
     * </pre>
     */
    boolean hasFileName();
    /**
     * <code>optional string fileName = 2;</code>
     *
     * <pre>
     *图片名称
     * </pre>
     */
    java.lang.String getFileName();
    /**
     * <code>optional string fileName = 2;</code>
     *
     * <pre>
     *图片名称
     * </pre>
     */
    com.google.protobuf.ByteString
        getFileNameBytes();
  }
  /**
   * Protobuf type {@code com.tworr.msg.Commons.ImageMessage}
   */
  public static final class ImageMessage extends
      com.google.protobuf.GeneratedMessage
      implements ImageMessageOrBuilder {
    // Use ImageMessage.newBuilder() to construct.
    private ImageMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ImageMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ImageMessage defaultInstance;
    public static ImageMessage getDefaultInstance() {
      return defaultInstance;
    }

    public ImageMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ImageMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              file_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              fileName_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tworr.msg.protocal.Commons.internal_static_com_tworr_msg_Commons_ImageMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tworr.msg.protocal.Commons.internal_static_com_tworr_msg_Commons_ImageMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tworr.msg.protocal.Commons.ImageMessage.class, com.tworr.msg.protocal.Commons.ImageMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<ImageMessage> PARSER =
        new com.google.protobuf.AbstractParser<ImageMessage>() {
      public ImageMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ImageMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ImageMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required bytes file = 1;
    public static final int FILE_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString file_;
    /**
     * <code>required bytes file = 1;</code>
     *
     * <pre>
     *图片内容
     * </pre>
     */
    public boolean hasFile() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes file = 1;</code>
     *
     * <pre>
     *图片内容
     * </pre>
     */
    public com.google.protobuf.ByteString getFile() {
      return file_;
    }

    // optional string fileName = 2;
    public static final int FILENAME_FIELD_NUMBER = 2;
    private java.lang.Object fileName_;
    /**
     * <code>optional string fileName = 2;</code>
     *
     * <pre>
     *图片名称
     * </pre>
     */
    public boolean hasFileName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string fileName = 2;</code>
     *
     * <pre>
     *图片名称
     * </pre>
     */
    public java.lang.String getFileName() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fileName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string fileName = 2;</code>
     *
     * <pre>
     *图片名称
     * </pre>
     */
    public com.google.protobuf.ByteString
        getFileNameBytes() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      file_ = com.google.protobuf.ByteString.EMPTY;
      fileName_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasFile()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, file_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getFileNameBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, file_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getFileNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.tworr.msg.protocal.Commons.ImageMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tworr.msg.protocal.Commons.ImageMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tworr.msg.protocal.Commons.ImageMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tworr.msg.protocal.Commons.ImageMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tworr.msg.protocal.Commons.ImageMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.tworr.msg.protocal.Commons.ImageMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.tworr.msg.protocal.Commons.ImageMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.tworr.msg.protocal.Commons.ImageMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.tworr.msg.protocal.Commons.ImageMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.tworr.msg.protocal.Commons.ImageMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.tworr.msg.protocal.Commons.ImageMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.tworr.msg.Commons.ImageMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.tworr.msg.protocal.Commons.ImageMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tworr.msg.protocal.Commons.internal_static_com_tworr_msg_Commons_ImageMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tworr.msg.protocal.Commons.internal_static_com_tworr_msg_Commons_ImageMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tworr.msg.protocal.Commons.ImageMessage.class, com.tworr.msg.protocal.Commons.ImageMessage.Builder.class);
      }

      // Construct using com.tworr.msg.protocal.Commons.ImageMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        file_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        fileName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tworr.msg.protocal.Commons.internal_static_com_tworr_msg_Commons_ImageMessage_descriptor;
      }

      public com.tworr.msg.protocal.Commons.ImageMessage getDefaultInstanceForType() {
        return com.tworr.msg.protocal.Commons.ImageMessage.getDefaultInstance();
      }

      public com.tworr.msg.protocal.Commons.ImageMessage build() {
        com.tworr.msg.protocal.Commons.ImageMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.tworr.msg.protocal.Commons.ImageMessage buildPartial() {
        com.tworr.msg.protocal.Commons.ImageMessage result = new com.tworr.msg.protocal.Commons.ImageMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.file_ = file_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.fileName_ = fileName_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tworr.msg.protocal.Commons.ImageMessage) {
          return mergeFrom((com.tworr.msg.protocal.Commons.ImageMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tworr.msg.protocal.Commons.ImageMessage other) {
        if (other == com.tworr.msg.protocal.Commons.ImageMessage.getDefaultInstance()) return this;
        if (other.hasFile()) {
          setFile(other.getFile());
        }
        if (other.hasFileName()) {
          bitField0_ |= 0x00000002;
          fileName_ = other.fileName_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasFile()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tworr.msg.protocal.Commons.ImageMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tworr.msg.protocal.Commons.ImageMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required bytes file = 1;
      private com.google.protobuf.ByteString file_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes file = 1;</code>
       *
       * <pre>
       *图片内容
       * </pre>
       */
      public boolean hasFile() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes file = 1;</code>
       *
       * <pre>
       *图片内容
       * </pre>
       */
      public com.google.protobuf.ByteString getFile() {
        return file_;
      }
      /**
       * <code>required bytes file = 1;</code>
       *
       * <pre>
       *图片内容
       * </pre>
       */
      public Builder setFile(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        file_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes file = 1;</code>
       *
       * <pre>
       *图片内容
       * </pre>
       */
      public Builder clearFile() {
        bitField0_ = (bitField0_ & ~0x00000001);
        file_ = getDefaultInstance().getFile();
        onChanged();
        return this;
      }

      // optional string fileName = 2;
      private java.lang.Object fileName_ = "";
      /**
       * <code>optional string fileName = 2;</code>
       *
       * <pre>
       *图片名称
       * </pre>
       */
      public boolean hasFileName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string fileName = 2;</code>
       *
       * <pre>
       *图片名称
       * </pre>
       */
      public java.lang.String getFileName() {
        java.lang.Object ref = fileName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          fileName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string fileName = 2;</code>
       *
       * <pre>
       *图片名称
       * </pre>
       */
      public com.google.protobuf.ByteString
          getFileNameBytes() {
        java.lang.Object ref = fileName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fileName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string fileName = 2;</code>
       *
       * <pre>
       *图片名称
       * </pre>
       */
      public Builder setFileName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        fileName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string fileName = 2;</code>
       *
       * <pre>
       *图片名称
       * </pre>
       */
      public Builder clearFileName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        fileName_ = getDefaultInstance().getFileName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string fileName = 2;</code>
       *
       * <pre>
       *图片名称
       * </pre>
       */
      public Builder setFileNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        fileName_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.tworr.msg.Commons.ImageMessage)
    }

    static {
      defaultInstance = new ImageMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.tworr.msg.Commons.ImageMessage)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tworr_msg_Commons_ResponseInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_tworr_msg_Commons_ResponseInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tworr_msg_Commons_SimpleUserInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_tworr_msg_Commons_SimpleUserInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tworr_msg_Commons_ImageMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_tworr_msg_Commons_ImageMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rCommoms.proto\022\025com.tworr.msg.Commons\"+" +
      "\n\014ResponseInfo\022\016\n\006status\030\001 \002(\005\022\013\n\003msg\030\002 " +
      "\001(\t\"r\n\016SimpleUserInfo\022\n\n\002id\030\001 \002(\t\022\020\n\010nic" +
      "kName\030\002 \002(\t\022\022\n\nheaderPath\030\003 \002(\t\022\r\n\005email" +
      "\030\004 \002(\t\022\r\n\005level\030\005 \001(\005\022\020\n\010isOnline\030\006 \002(\010\"" +
      ".\n\014ImageMessage\022\014\n\004file\030\001 \002(\014\022\020\n\010fileNam" +
      "e\030\002 \001(\tB!\n\026com.tworr.msg.protocalB\007Commo" +
      "ns"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_tworr_msg_Commons_ResponseInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_tworr_msg_Commons_ResponseInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_tworr_msg_Commons_ResponseInfo_descriptor,
              new java.lang.String[] { "Status", "Msg", });
          internal_static_com_tworr_msg_Commons_SimpleUserInfo_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_tworr_msg_Commons_SimpleUserInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_tworr_msg_Commons_SimpleUserInfo_descriptor,
              new java.lang.String[] { "Id", "NickName", "HeaderPath", "Email", "Level", "IsOnline", });
          internal_static_com_tworr_msg_Commons_ImageMessage_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_tworr_msg_Commons_ImageMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_tworr_msg_Commons_ImageMessage_descriptor,
              new java.lang.String[] { "File", "FileName", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
